import Foundation

extension DivinationCard {
    static let ganeshaCards: [DivinationCard] = [
        DivinationCard(id: "ganesha_1", number: 1, suit: .dharma, deityID: .ganesha, nameEN: "Pratham Pujya", nameZH: "首祭尊者", nameHI: "प्रथम पूज्य", meaningEN: "First Among All", meaningZH: "万事之先", meaningHI: "सबसे पहले पूज्य", descEN: "Ganesha sits upon a golden lotus throne in radiant light, gods on both sides bow in reverence.", descZH: "金光中象头神端坐莲台，众神于两侧合掌敬拜", descHI: "गणेश स्वर्णिम प्रकाश में कमल सिंहासन पर विराजमान हैं, दोनों ओर देवता श्रद्धापूर्वक नमन करते हैं"),
        DivinationCard(id: "ganesha_2", number: 2, suit: .dharma, deityID: .ganesha, nameEN: "Om Kara", nameZH: "唵字圣音", nameHI: "ओंकार", meaningEN: "Universal Foundation", meaningZH: "宇宙根本", meaningHI: "सार्वभौमिक आधार", descEN: "A golden Om symbol floats before Ganesha's chest, its sound waves expanding outward in concentric rings of light.", descZH: "象头神胸前浮现金色唵字，音波化为层层光环扩散", descHI: "गणेश के वक्ष के सामने स्वर्णिम ॐ तैरता है, ध्वनि तरंगें प्रकाश वलयों में फैलती हैं"),
        DivinationCard(id: "ganesha_3", number: 3, suit: .dharma, deityID: .ganesha, nameEN: "Mahabharata Scribe", nameZH: "史诗书记", nameHI: "महाभारत लेखक", meaningEN: "Truth Carried by Dharma", meaningZH: "真理载道", meaningHI: "धर्म द्वारा वहन सत्य", descEN: "Ganesha writes with his broken tusk as a pen, inscribing Sanskrit scriptures on palm leaves.", descZH: "象头神持断牙为笔，于棕榈叶上书写梵文经典", descHI: "गणेश टूटे दांत को कलम बनाकर ताड़पत्र पर संस्कृत शास्त्र लिखते हैं"),
        DivinationCard(id: "ganesha_4", number: 4, suit: .dharma, deityID: .ganesha, nameEN: "Dharma Chakra", nameZH: "法轮常转", nameHI: "धर्म चक्र", meaningEN: "Eternal Dharma", meaningZH: "正法不灭", meaningHI: "शाश्वत धर्म", descEN: "Four-armed Ganesha turns the golden dharma wheel, its eight spokes radiating the light of the eightfold path.", descZH: "象头神四臂转动金色法轮，轮辐射出八道正道之光", descHI: "चतुर्भुज गणेश स्वर्ण धर्म चक्र घुमाते हैं, आठ अरे अष्टांग मार्ग का प्रकाश विकीर्ण करती हैं"),
        DivinationCard(id: "ganesha_5", number: 5, suit: .dharma, deityID: .ganesha, nameEN: "Vidya Pati", nameZH: "学问之主", nameHI: "विद्या पति", meaningEN: "Knowledge Illuminates", meaningZH: "智识照暗", meaningHI: "ज्ञान प्रकाशित करता है", descEN: "Ganesha sits among stacks of scrolls, holding a scripture while the gem on his forehead glows.", descZH: "象头神端坐书卷堆中，手托经典，额间宝石发光", descHI: "गणेश ग्रंथों के ढेर में बैठे हैं, शास्त्र धारण किए, माथे का रत्न चमकता है"),
        DivinationCard(id: "ganesha_6", number: 6, suit: .dharma, deityID: .ganesha, nameEN: "Mangala Murti", nameZH: "吉祥化身", nameHI: "मंगल मूर्ति", meaningEN: "Source of All Blessings", meaningZH: "万福根源", meaningHI: "सभी आशीर्वादों का स्रोत", descEN: "Red Ganesha adorned with golden ornaments, surrounded by auspicious grain and lotus flowers.", descZH: "红色象头神身披金饰，周围环绕吉祥稻穗与莲花", descHI: "स्वर्ण आभूषणों से सुशोभित लाल गणेश, शुभ अन्न और कमल पुष्पों से घिरे"),
        DivinationCard(id: "ganesha_7", number: 7, suit: .dharma, deityID: .ganesha, nameEN: "Satya Vachana", nameZH: "真语守信", nameHI: "सत्य वचन", meaningEN: "Words Manifest Truth", meaningZH: "言出必成", meaningHI: "शब्द सत्य प्रकट करते हैं", descEN: "Ganesha raises one hand to heaven and touches earth with the other, golden Sanskrit mantras flowing from his mouth.", descZH: "象头神一手举天一手触地，口中吐出金色梵文真言", descHI: "गणेश एक हाथ स्वर्ग की ओर उठाते हैं और दूसरे से पृथ्वी छूते हैं, मुख से स्वर्ण संस्कृत मंत्र प्रवाहित होते हैं"),
        DivinationCard(id: "ganesha_8", number: 8, suit: .dharma, deityID: .ganesha, nameEN: "Nritya Ganapati", nameZH: "舞王象神", nameHI: "नृत्य गणपति", meaningEN: "Cosmic Harmony", meaningZH: "天地和谐", meaningHI: "ब्रह्मांडीय सामंजस्य", descEN: "Ganesha dances gracefully within a ring of fire, eight arms each holding a divine instrument.", descZH: "象头神于火焰圆环中翩翩起舞，八臂各持法器", descHI: "गणेश अग्नि वलय में सुंदर नृत्य करते हैं, आठ भुजाओं में दिव्य उपकरण धारण किए"),

        DivinationCard(id: "ganesha_9", number: 9, suit: .karma, deityID: .ganesha, nameEN: "Vighneshwara", nameZH: "除障圣主", nameHI: "विघ्नेश्वर", meaningEN: "All Obstacles Shatter", meaningZH: "诸障皆破", meaningHI: "सभी बाधाएं टूटती हैं", descEN: "Ganesha stamps upon boulders, his four arms pushing apart two cracking black mountains.", descZH: "象头神脚踏巨石，四臂奋力推开两座崩裂的黑色山岩", descHI: "गणेश शिलाओं पर पैर रखते हैं, चार भुजाओं से दो टूटते काले पर्वतों को खोलते हैं"),
        DivinationCard(id: "ganesha_10", number: 10, suit: .karma, deityID: .ganesha, nameEN: "Ankusha", nameZH: "神圣象钩", nameHI: "अंकुश", meaningEN: "Taming the Mind", meaningZH: "驯心归正", meaningHI: "मन को वश में करना", descEN: "Ganesha raises the golden goad high, its tip blazing with fire to dispel the mist of darkness.", descZH: "象头神高举金色象钩，钩尖发出烈焰驱散黑暗迷雾", descHI: "गणेश स्वर्ण अंकुश ऊंचा उठाते हैं, इसकी नोक अग्नि से अंधकार की धुंध को दूर करती है"),
        DivinationCard(id: "ganesha_11", number: 11, suit: .karma, deityID: .ganesha, nameEN: "Mushak Vahana", nameZH: "神鼠坐骑", nameHI: "मूषक वाहन", meaningEN: "Small Carries Great", meaningZH: "以小驭大", meaningHI: "छोटा बड़े को वहन करता है", descEN: "A small gray mouse carries the great Ganesha along a rocky mountain path, advancing steadily.", descZH: "小灰鼠驮载巨大象头神穿行于崎岖山路坚定前行", descHI: "छोटा मूषक विशाल गणेश को पथरीले पर्वत मार्ग पर ले जाता है, दृढ़ता से आगे बढ़ता है"),
        DivinationCard(id: "ganesha_12", number: 12, suit: .karma, deityID: .ganesha, nameEN: "Pasha", nameZH: "神圣绳索", nameHI: "पाश", meaningEN: "Binding Attachment", meaningZH: "缚执破贪", meaningHI: "आसक्ति बांधती है", descEN: "Ganesha swings the golden noose, lassoing three dark serpents that symbolize greed, anger, and delusion.", descZH: "象头神挥舞金色绳索，套住象征贪嗔痴的三头暗蛇", descHI: "गणेश स्वर्ण पाश फेंकते हैं, लोभ, क्रोध और मोह के प्रतीक तीन अंधेरे नागों को बांधते हैं"),
        DivinationCard(id: "ganesha_13", number: 13, suit: .karma, deityID: .ganesha, nameEN: "Parashu", nameZH: "战斧断执", nameHI: "परशु", meaningEN: "Cutting Old Karma", meaningZH: "斩断旧业", meaningHI: "पुराने कर्म काटना", descEN: "Ganesha lifts the crescent battle axe, cleaving apart the thorny vines entangling himself.", descZH: "象头神举起月牙战斧，劈开缠绕自身的荆棘枯藤", descHI: "गणेश अर्धचंद्राकार परशु उठाते हैं, अपने चारों ओर लिपटी कंटीली लताओं को काटते हैं"),
        DivinationCard(id: "ganesha_14", number: 14, suit: .karma, deityID: .ganesha, nameEN: "Heramba", nameZH: "五面勇象", nameHI: "हेरंब", meaningEN: "Fearless Advance", meaningZH: "勇行不退", meaningHI: "निडर आगे बढ़ना", descEN: "Five-faced, ten-armed Ganesha rides a lion, charging majestically across the battlefield.", descZH: "五面十臂象头神骑雄狮，威风凛凛驰骋于战场之上", descHI: "पंचमुखी, दस भुजाओं वाले गणेश सिंह पर सवार, युद्धभूमि में भव्यता से आगे बढ़ते हैं"),
        DivinationCard(id: "ganesha_15", number: 15, suit: .karma, deityID: .ganesha, nameEN: "Gaja Hasta", nameZH: "象鼻卷物", nameHI: "गज हस्त", meaningEN: "Diligent Effort", meaningZH: "精进不懈", meaningHI: "अथक प्रयास", descEN: "Ganesha's long trunk curls around a golden modaka, beside an unfinished workbench.", descZH: "象头神长鼻卷起金色莫达卡，旁有未完成的工作台", descHI: "गणेश की लंबी सूंड स्वर्ण मोदक को लपेटती है, पास में अधूरी कार्यशाला"),
        DivinationCard(id: "ganesha_16", number: 16, suit: .karma, deityID: .ganesha, nameEN: "Ekadanta", nameZH: "独牙圣者", nameHI: "एकदंत", meaningEN: "Sacrifice for Purpose", meaningZH: "舍身成业", meaningHI: "उद्देश्य के लिए त्याग", descEN: "Ganesha holds his own broken tusk, golden ink dripping from its tip.", descZH: "象头神手持自己折断的象牙，牙尖滴下金色墨汁", descHI: "गणेश अपना टूटा दांत पकड़े हैं, इसकी नोक से स्वर्ण स्याही टपकती है"),

        DivinationCard(id: "ganesha_17", number: 17, suit: .kama, deityID: .ganesha, nameEN: "Modaka", nameZH: "摩达迦甜", nameHI: "मोदक", meaningEN: "Sweetness of Fulfilled Wishes", meaningZH: "心愿甘蜜", meaningHI: "पूर्ण इच्छाओं की मिठास", descEN: "Ganesha joyfully holds a golden sweet dumpling, a bowl of modakas piled high like a small mountain.", descZH: "象头神欢喜捧食金色甜团，碗中摩达迦堆如小山", descHI: "गणेश प्रसन्नतापूर्वक स्वर्ण मोदक धारण करते हैं, पात्र में मोदकों का पर्वत सा ढेर"),
        DivinationCard(id: "ganesha_18", number: 18, suit: .kama, deityID: .ganesha, nameEN: "Siddhi-Buddhi", nameZH: "悉地菩提", nameHI: "सिद्धि-बुद्धि", meaningEN: "Achievement and Wisdom", meaningZH: "成就智慧", meaningHI: "सिद्धि और बुद्धि", descEN: "Ganesha sits flanked by his two consorts Siddhi and Buddhi, all three sharing a lotus throne.", descZH: "象头神左拥悉地右拥菩提二妃，三者同坐莲花宝座", descHI: "गणेश दोनों ओर सिद्धि और बुद्धि के साथ विराजमान, तीनों कमल सिंहासन साझा करते हैं"),
        DivinationCard(id: "ganesha_19", number: 19, suit: .kama, deityID: .ganesha, nameEN: "Bala Ganapati", nameZH: "童子象神", nameHI: "बाल गणपति", meaningEN: "Original Innocence", meaningZH: "赤子初心", meaningHI: "मूल निर्दोषता", descEN: "Red child Ganesha holds mangoes, bananas, and sugarcane, his smile pure and innocent.", descZH: "红色幼年象头神手持芒果香蕉甘蔗笑容天真烂漫", descHI: "लाल बालक गणेश आम, केला और गन्ना पकड़े हैं, उनकी मुस्कान शुद्ध और निर्दोष"),
        DivinationCard(id: "ganesha_20", number: 20, suit: .kama, deityID: .ganesha, nameEN: "Pushpa Mala", nameZH: "花鬘供养", nameHI: "पुष्प माला", meaningEN: "Devotion Moves Heaven", meaningZH: "虔诚感天", meaningHI: "भक्ति स्वर्ग को हिलाती है", descEN: "Devotees hold a garland of red hibiscus flowers, offering it reverently around Ganesha's neck.", descZH: "信徒双手捧红色木槿花环，敬献于象头神颈项之上", descHI: "भक्त लाल जवाकुसुम की माला दोनों हाथों से पकड़कर गणेश के गले में श्रद्धापूर्वक अर्पित करते हैं"),
        DivinationCard(id: "ganesha_21", number: 21, suit: .kama, deityID: .ganesha, nameEN: "Durva Puja", nameZH: "圣草祈愿", nameHI: "दूर्वा पूजा", meaningEN: "Small Offerings, Deep Feeling", meaningZH: "微物寄情", meaningHI: "छोटे अर्पण, गहरी भावना", descEN: "Twenty-one tender green durva grass blades bundled and placed at Ganesha's feet.", descZH: "二十一根嫩绿杜尔瓦草扎束供于象头神足前石台", descHI: "इक्कीस कोमल हरी दूर्वा घास की गुच्छी गणेश के चरणों में अर्पित"),
        DivinationCard(id: "ganesha_22", number: 22, suit: .kama, deityID: .ganesha, nameEN: "Shubha Labha", nameZH: "吉庆丰获", nameHI: "शुभ लाभ", meaningEN: "Wishes Fulfilled", meaningZH: "善愿圆满", meaningHI: "इच्छाएं पूर्ण", descEN: "Ganesha's two sons Shubha and Labha stand on either side, hands full of treasures and fruits.", descZH: "象头神二子吉庆与丰获侍立两旁手捧珍宝果实", descHI: "गणेश के दो पुत्र शुभ और लाभ दोनों ओर खड़े हैं, हाथों में रत्न और फल भरे"),
        DivinationCard(id: "ganesha_23", number: 23, suit: .kama, deityID: .ganesha, nameEN: "Vallabha", nameZH: "钟爱之主", nameHI: "वल्लभ", meaningEN: "Nectar of Love", meaningZH: "爱之甘露", meaningHI: "प्रेम का अमृत", descEN: "Ganesha embraces a veena in a moonlit garden, music notes transforming into dancing butterflies.", descZH: "象头神怀抱琵琶于月光花园弹奏音符化蝶飞舞", descHI: "गणेश चांदनी बगीचे में वीणा बजाते हैं, स्वर तितलियों में बदलकर नृत्य करते हैं"),
        DivinationCard(id: "ganesha_24", number: 24, suit: .kama, deityID: .ganesha, nameEN: "Abhaya Mudra", nameZH: "无畏施印", nameHI: "अभय मुद्रा", meaningEN: "Fear Not, Be at Peace", meaningZH: "安心无惧", meaningHI: "भय न करो, शांत रहो", descEN: "Ganesha extends his right palm outward in the fearless gesture, radiating warm golden light.", descZH: "象头神右掌向外结无畏印掌心放射温暖柔和金光", descHI: "गणेश दाहिना हाथ अभय मुद्रा में बाहर की ओर करते हैं, हथेली से गर्म स्वर्णिम प्रकाश निकलता है"),

        DivinationCard(id: "ganesha_25", number: 25, suit: .moksha, deityID: .ganesha, nameEN: "Broken Tusk", nameZH: "断牙献祭", nameHI: "खंडित दंत", meaningEN: "Breaking Attachment for Freedom", meaningZH: "破执自在", meaningHI: "मुक्ति के लिए आसक्ति तोड़ना", descEN: "The broken tusk falls to earth becoming ten thousand rays of golden light, Ganesha smiles looking down.", descZH: "断牙落地化为金光万道，象头神微笑俯视残牙", descHI: "टूटा दांत पृथ्वी पर गिरकर हजारों स्वर्ण किरणें बनता है, गणेश मुस्कुराते हुए नीचे देखते हैं"),
        DivinationCard(id: "ganesha_26", number: 26, suit: .moksha, deityID: .ganesha, nameEN: "Siddhi Vinayaka", nameZH: "成就自在", nameHI: "सिद्धि विनायक", meaningEN: "Supreme Attainment", meaningZH: "修成无上", meaningHI: "सर्वोच्च प्राप्ति", descEN: "Ganesha radiates white light from his entire being, sitting in meditation upon a thousand-petaled golden lotus.", descZH: "象头神全身放射白光，盘坐于千瓣金莲之上入定", descHI: "गणेश संपूर्ण शरीर से श्वेत प्रकाश विकीर्ण करते हैं, सहस्र दल स्वर्ण कमल पर ध्यानस्थ"),
        DivinationCard(id: "ganesha_27", number: 27, suit: .moksha, deityID: .ganesha, nameEN: "Mula Dhara", nameZH: "根轮觉醒", nameHI: "मूलाधार", meaningEN: "Root Awakening", meaningZH: "灵蛇升觉", meaningHI: "मूल जागृति", descEN: "Ganesha sits upon the red four-petaled root chakra as the kundalini serpent rises along the spine.", descZH: "象头神盘坐于红色四瓣根轮之上拙火蛇沿脊柱上升", descHI: "गणेश लाल चार पंखुड़ी वाले मूलाधार चक्र पर बैठे हैं, कुंडलिनी सर्प रीढ़ के सहारे ऊपर उठता है"),
        DivinationCard(id: "ganesha_28", number: 28, suit: .moksha, deityID: .ganesha, nameEN: "Buddhi Deva", nameZH: "觉慧之神", nameHI: "बुद्धि देव", meaningEN: "Piercing Ignorance", meaningZH: "照破无明", meaningHI: "अज्ञान का भेदन", descEN: "Ganesha's third eye opens wide, three beams of light piercing through layers of dark clouds.", descZH: "象头神额间第三眼大开三道光芒穿透层层黑暗云雾", descHI: "गणेश का तीसरा नेत्र पूरा खुलता है, तीन प्रकाश किरणें अंधकार के बादलों को भेदती हैं"),
        DivinationCard(id: "ganesha_29", number: 29, suit: .moksha, deityID: .ganesha, nameEN: "Vighna Vinashaka", nameZH: "灭障解脱", nameHI: "विघ्न विनाशक", meaningEN: "Liberation Without Obstacles", meaningZH: "无障涅槃", meaningHI: "बाधा रहित मुक्ति", descEN: "Ganesha sits in the void as chains shatter around him, fragments transforming into stars.", descZH: "象头神端坐虚空周身锁链碎裂纷飞化为星辰", descHI: "गणेश शून्य में बैठे हैं, उनके चारों ओर जंजीरें टूटती हैं, टुकड़े तारों में बदल जाते हैं"),
        DivinationCard(id: "ganesha_30", number: 30, suit: .moksha, deityID: .ganesha, nameEN: "Pranava Svarupa", nameZH: "唵之化身", nameHI: "प्रणव स्वरूप", meaningEN: "All Returns to One", meaningZH: "万法归一", meaningHI: "सब एक में लौटता है", descEN: "Ganesha's body transforms into a great golden Om symbol, merging into the vast cosmic universe.", descZH: "象头神身躯化为巨大金色唵字融入浩瀚星空宇宙", descHI: "गणेश का शरीर विशाल स्वर्ण ॐ में रूपांतरित होता है, विस्तृत ब्रह्मांड में विलीन"),
        DivinationCard(id: "ganesha_31", number: 31, suit: .moksha, deityID: .ganesha, nameEN: "Akasha Ganesha", nameZH: "虚空象神", nameHI: "आकाश गणेश", meaningEN: "Emptiness Complete", meaningZH: "空性圆满", meaningHI: "शून्यता पूर्ण", descEN: "A transparent Ganesha sits amid the Milky Way, his body merging as one with the cosmic void.", descZH: "透明象头神端坐于星河之中身体与宇宙虚空合一", descHI: "पारदर्शी गणेश आकाशगंगा में बैठे हैं, उनका शरीर ब्रह्मांडीय शून्य के साथ एकाकार"),
        DivinationCard(id: "ganesha_32", number: 32, suit: .moksha, deityID: .ganesha, nameEN: "Param Brahma", nameZH: "至上梵天", nameHI: "परम ब्रह्म", meaningEN: "Ultimate Liberation", meaningZH: "究竟解脱", meaningHI: "परम मुक्ति", descEN: "Ganesha dissolves into pure formless white light, within which faintly appears the cycle of all cosmic phenomena.", descZH: "象头神化为纯净无形白光，光中隐现宇宙万象轮回", descHI: "गणेश शुद्ध निराकार श्वेत प्रकाश में विलीन होते हैं, जिसमें ब्रह्मांड की सभी घटनाओं का चक्र धुंधला दिखता है"),
    ]
}
