import Foundation

extension DivinationCard {
    static let hanumanCards: [DivinationCard] = [
        DivinationCard(id: "hanuman_1", number: 1, suit: .dharma, deityID: .hanuman, nameEN: "Ram Sevak", nameZH: "罗摩侍者", nameHI: "राम सेवक", meaningEN: "Supreme Devotion", meaningZH: "至诚侍奉", meaningHI: "परम भक्ति", descEN: "Hanuman kneels before Rama with palms joined, an eternal servant of unwavering loyalty.", descZH: "哈努曼双手合十跪于罗摩足前永为忠仆", descHI: "हनुमान हाथ जोड़कर राम के चरणों में घुटने टेकते हैं, अटल निष्ठा के शाश्वत सेवक"),
        DivinationCard(id: "hanuman_2", number: 2, suit: .dharma, deityID: .hanuman, nameEN: "Pratigya", nameZH: "神圣誓言", nameHI: "प्रतिज्ञा", meaningEN: "Sacred Vow", meaningZH: "誓守正法", meaningHI: "पवित्र प्रतिज्ञा", descEN: "Hanuman places his hand on his heart before the sacred fire, taking an unbreakable vow.", descZH: "哈努曼手按胸口于圣火前立下不破之誓", descHI: "हनुमान पवित्र अग्नि के समक्ष हृदय पर हाथ रखकर अटूट प्रतिज्ञा लेते हैं"),
        DivinationCard(id: "hanuman_3", number: 3, suit: .dharma, deityID: .hanuman, nameEN: "Dharma Rakshak", nameZH: "护法者", nameHI: "धर्म रक्षक", meaningEN: "Guardian of Righteousness", meaningZH: "守护正义", meaningHI: "धर्म का रक्षक", descEN: "Hanuman stands with banner at the boundary of good and evil, defending the law.", descZH: "哈努曼持旗屹立于善恶交界处捍卫法则", descHI: "हनुमान ध्वज लेकर अच्छाई और बुराई की सीमा पर खड़े हैं, धर्म की रक्षा करते हैं"),
        DivinationCard(id: "hanuman_4", number: 4, suit: .dharma, deityID: .hanuman, nameEN: "Brahmachari", nameZH: "梵行者", nameHI: "ब्रह्मचारी", meaningEN: "Pure Discipline", meaningZH: "清净持戒", meaningHI: "शुद्ध अनुशासन", descEN: "Hanuman sits upon a lotus throne draped in deerskin, his aura pure and untainted.", descZH: "哈努曼端坐莲台身披鹿皮光芒纯净无染", descHI: "हनुमान मृगचर्म ओढ़े कमल सिंहासन पर बैठे हैं, उनकी आभा शुद्ध और निर्मल"),
        DivinationCard(id: "hanuman_5", number: 5, suit: .dharma, deityID: .hanuman, nameEN: "Vanara Sena", nameZH: "猴军统帅", nameHI: "वानर सेना", meaningEN: "Leading All Beings", meaningZH: "引领众生", meaningHI: "सभी प्राणियों का नेतृत्व", descEN: "Hanuman stands atop a mountain peak, commanding a vast monkey army to march toward righteousness.", descZH: "哈努曼立于山巅指挥万千猴军奔赴正义之战", descHI: "हनुमान पर्वत शिखर पर खड़े होकर विशाल वानर सेना को धर्म युद्ध का आदेश देते हैं"),
        DivinationCard(id: "hanuman_6", number: 6, suit: .dharma, deityID: .hanuman, nameEN: "Guru Surya", nameZH: "拜日为师", nameHI: "गुरु सूर्य", meaningEN: "Humble Learning", meaningZH: "谦学正道", meaningHI: "विनम्र शिक्षा", descEN: "Young Hanuman flies toward the sun, humbly seeking the Sun God as his teacher.", descZH: "幼年哈努曼飞向太阳虔诚拜日神为师", descHI: "बालक हनुमान सूर्य की ओर उड़ते हैं, विनम्रता से सूर्य देव को गुरु मानते हैं"),
        DivinationCard(id: "hanuman_7", number: 7, suit: .dharma, deityID: .hanuman, nameEN: "Setu Sevak", nameZH: "造桥奉献", nameHI: "सेतु सेवक", meaningEN: "Selfless Service", meaningZH: "无私奉行", meaningHI: "निःस्वार्थ सेवा", descEN: "Hanuman carries great boulders and casts them into the sea, helping build Rama's bridge.", descZH: "哈努曼搬运巨石投入大海助建罗摩神桥", descHI: "हनुमान विशाल शिलाएं उठाकर समुद्र में डालते हैं, राम सेतु निर्माण में सहायता करते हैं"),
        DivinationCard(id: "hanuman_8", number: 8, suit: .dharma, deityID: .hanuman, nameEN: "Ashoka Vana", nameZH: "阿育园使", nameHI: "अशोक वन", meaningEN: "Fearless Truth-Bearer", meaningZH: "传法无畏", meaningHI: "निडर सत्य वाहक", descEN: "Hanuman sits in the Ashoka garden, fearlessly proclaiming dharma before the demon host.", descZH: "哈努曼端坐阿育园中于罗刹众前宣说正法", descHI: "हनुमान अशोक वाटिका में बैठकर राक्षसों के समक्ष निडर होकर धर्म का प्रचार करते हैं"),

        DivinationCard(id: "hanuman_9", number: 9, suit: .karma, deityID: .hanuman, nameEN: "Lanka Leap", nameZH: "跃海飞渡", nameHI: "लंका छलांग", meaningEN: "Bold Action", meaningZH: "勇猛精进", meaningHI: "साहसिक कर्म", descEN: "Hanuman leaps across the vast ocean, flying toward the island of Lanka.", descZH: "哈努曼纵身一跃横跨沧海飞向楞伽之岛", descHI: "हनुमान विशाल सागर को एक छलांग में पार कर लंका की ओर उड़ते हैं"),
        DivinationCard(id: "hanuman_10", number: 10, suit: .karma, deityID: .hanuman, nameEN: "Burning Lanka", nameZH: "火烧楞伽", nameHI: "लंका दहन", meaningEN: "Karma Fire Manifests", meaningZH: "业火昭彰", meaningHI: "कर्म अग्नि प्रकट", descEN: "Hanuman sweeps his burning tail across Lanka, flames consuming the demon king's capital.", descZH: "哈努曼燃尾扫过楞伽城烈焰吞噬罗刹王都", descHI: "हनुमान जलती पूंछ से लंका को बहाते हैं, अग्नि राक्षस राज की राजधानी को निगल लेती है"),
        DivinationCard(id: "hanuman_11", number: 11, suit: .karma, deityID: .hanuman, nameEN: "Sanjeevani", nameZH: "灵山神药", nameHI: "संजीवनी", meaningEN: "Life-Saving Action", meaningZH: "济世救命", meaningHI: "जीवन रक्षक कर्म", descEN: "Hanuman carries the entire mountain of healing herbs, flying through the sky to save the hero.", descZH: "哈努曼托举整座药草山飞越长空救治英雄", descHI: "हनुमान संपूर्ण औषधि पर्वत उठाकर आकाश में उड़ते हैं, वीर की प्राण रक्षा के लिए"),
        DivinationCard(id: "hanuman_12", number: 12, suit: .karma, deityID: .hanuman, nameEN: "Gada", nameZH: "金刚神杵", nameHI: "गदा", meaningEN: "Crushing Obstacles", meaningZH: "降魔伏恶", meaningHI: "बाधाओं का विनाश", descEN: "Hanuman raises his mighty mace with fierce eyes, crushing all obstacles to dust.", descZH: "哈努曼高举金刚杵怒目圆睁粉碎一切障碍", descHI: "हनुमान क्रोधित नेत्रों से शक्तिशाली गदा उठाते हैं, सभी बाधाओं को चूर-चूर करते हैं"),
        DivinationCard(id: "hanuman_13", number: 13, suit: .karma, deityID: .hanuman, nameEN: "Dronagiri", nameZH: "举山之力", nameHI: "द्रोणगिरि", meaningEN: "No Task Too Great", meaningZH: "不惧艰巨", meaningHI: "कोई कार्य बड़ा नहीं", descEN: "Hanuman lifts the towering mountain with one palm, treading clouds and flying at dawn.", descZH: "哈努曼单掌托起巍峨山峰脚踏祥云破晓飞行", descHI: "हनुमान एक हथेली से विशाल पर्वत उठाते हैं, बादलों पर चलते हुए भोर में उड़ते हैं"),
        DivinationCard(id: "hanuman_14", number: 14, suit: .karma, deityID: .hanuman, nameEN: "Surasa Vijay", nameZH: "胜蛇母", nameHI: "सुरसा विजय", meaningEN: "Wisdom Overcomes Obstacles", meaningZH: "智破险阻", meaningHI: "बुद्धि से बाधा पार", descEN: "Hanuman shrinks himself to pass through the serpent mother's mouth, overcoming the trial with wisdom.", descZH: "哈努曼缩身穿越蛇母巨口以智慧化解劫难", descHI: "हनुमान सुरसा के विशाल मुख से सूक्ष्म होकर निकलते हैं, बुद्धि से संकट का समाधान करते हैं"),
        DivinationCard(id: "hanuman_15", number: 15, suit: .karma, deityID: .hanuman, nameEN: "Aksha Vadha", nameZH: "战阿叉", nameHI: "अक्ष वध", meaningEN: "Courageous Battle", meaningZH: "果敢应战", meaningHI: "साहसी युद्ध", descEN: "Hanuman fights valiantly before Lanka's palace, confronting the demon prince and his army.", descZH: "哈努曼于楞伽宫前奋力迎战罗刹太子群敌", descHI: "हनुमान लंका के राजमहल के सामने वीरता से लड़ते हैं, राक्षस राजकुमार और उसकी सेना का सामना करते हैं"),
        DivinationCard(id: "hanuman_16", number: 16, suit: .karma, deityID: .hanuman, nameEN: "Mayavi Yuddha", nameZH: "幻战克敌", nameHI: "मायावी युद्ध", meaningEN: "Breaking Through Illusion", meaningZH: "破除幻象", meaningHI: "माया का भेदन", descEN: "Hanuman sees through the battlefield's illusions, cutting through the maze of deception with righteous mind.", descZH: "哈努曼识破战场魔幻以正念之力斩断迷阵", descHI: "हनुमान युद्धभूमि की माया को पहचानते हैं, सत्य चेतना से भ्रम जाल को काटते हैं"),

        DivinationCard(id: "hanuman_17", number: 17, suit: .kama, deityID: .hanuman, nameEN: "Hridaya Rama", nameZH: "心中之主", nameHI: "हृदय राम", meaningEN: "Pure Love Within", meaningZH: "至爱纯诚", meaningHI: "हृदय में शुद्ध प्रेम", descEN: "Hanuman tears open his chest revealing the image of Rama and Sita dwelling within his heart.", descZH: "哈努曼撕开胸膛心中显现罗摩悉多圣像", descHI: "हनुमान अपनी छाती फाड़ते हैं, हृदय में राम और सीता की छवि प्रकट होती है"),
        DivinationCard(id: "hanuman_18", number: 18, suit: .kama, deityID: .hanuman, nameEN: "Bal Hanuman", nameZH: "神童哈努曼", nameHI: "बाल हनुमान", meaningEN: "Childlike Wonder", meaningZH: "赤子天真", meaningHI: "बालसुलभ आश्चर्य", descEN: "Baby Hanuman soars through the clouds chasing the sun, innocent and fearless.", descZH: "幼年哈努曼腾云追日天真烂漫无所畏惧", descHI: "बालक हनुमान बादलों में सूर्य का पीछा करते हुए उड़ते हैं, निर्दोष और निडर"),
        DivinationCard(id: "hanuman_19", number: 19, suit: .kama, deityID: .hanuman, nameEN: "Sita Bhakti", nameZH: "寻母至诚", nameHI: "सीता भक्ति", meaningEN: "Loyal Seeking", meaningZH: "忠诚寻觅", meaningHI: "निष्ठावान खोज", descEN: "Hanuman carries Rama's token, searching for Sita under the moonlight with unwavering devotion.", descZH: "哈努曼捧持罗摩信物于月下寻觅悉多女神", descHI: "हनुमान राम की निशानी लेकर चांदनी में अटल भक्ति से सीता की खोज करते हैं"),
        DivinationCard(id: "hanuman_20", number: 20, suit: .kama, deityID: .hanuman, nameEN: "Chudamani", nameZH: "珠冠信物", nameHI: "चूडामणि", meaningEN: "Token of Love", meaningZH: "爱之凭证", meaningHI: "प्रेम का प्रतीक", descEN: "Hanuman reverently presents Sita's crown jewel to Rama, his eyes brimming with tears.", descZH: "哈努曼双手恭捧悉多发冠宝珠泪目呈于罗摩", descHI: "हनुमान श्रद्धापूर्वक सीता की चूड़ामणि राम को अर्पित करते हैं, आंखों में आंसू भरे हुए"),
        DivinationCard(id: "hanuman_21", number: 21, suit: .kama, deityID: .hanuman, nameEN: "Nama Japa", nameZH: "圣名持诵", nameHI: "नाम जप", meaningEN: "Ceaseless Devotion", meaningZH: "虔诚不断", meaningHI: "अविरत भक्ति", descEN: "Hanuman sits with eyes closed, ceaselessly chanting Rama's sacred name.", descZH: "哈努曼闭目端坐口中不断念诵罗摩圣名", descHI: "हनुमान आंखें बंद करके बैठे हैं, अविरत राम नाम का जप करते हुए"),
        DivinationCard(id: "hanuman_22", number: 22, suit: .kama, deityID: .hanuman, nameEN: "Anjaneyar", nameZH: "风神之子", nameHI: "आंजनेय", meaningEN: "Deep Innate Love", meaningZH: "天赋深情", meaningHI: "जन्मजात गहरा प्रेम", descEN: "Anjana cradles baby Hanuman as Vayu the Wind God descends with blessings.", descZH: "安佳娜怀抱婴儿哈努曼风神伐由飘然降福", descHI: "अंजना शिशु हनुमान को गोद में लिए हैं, वायु देव आशीर्वाद लेकर अवतरित होते हैं"),
        DivinationCard(id: "hanuman_23", number: 23, suit: .kama, deityID: .hanuman, nameEN: "Prema Sevak", nameZH: "爱之仆从", nameHI: "प्रेम सेवक", meaningEN: "Service Through Love", meaningZH: "以爱奉献", meaningHI: "प्रेम से सेवा", descEN: "Hanuman washes Rama's feet with tears, gently drying them with his hair, full of deep devotion.", descZH: "哈努曼含泪为罗摩洗足以发轻拭满怀深情", descHI: "हनुमान आंसुओं से राम के चरण धोते हैं, बालों से कोमलता से पोंछते हैं, गहरी भक्ति से भरे"),
        DivinationCard(id: "hanuman_24", number: 24, suit: .kama, deityID: .hanuman, nameEN: "Sankat Mochan", nameZH: "除障济苦", nameHI: "संकट मोचन", meaningEN: "Compassion Rescues All", meaningZH: "悲愿度众", meaningHI: "करुणा सबको बचाती है", descEN: "Hanuman reaches down from auspicious clouds, his great hand lifting those who pray from their suffering.", descZH: "哈努曼自祥云伸出巨掌接引苦难中祈求之人", descHI: "हनुमान शुभ बादलों से विशाल हाथ बढ़ाते हैं, प्रार्थना करने वालों को कष्ट से उठाते हैं"),

        DivinationCard(id: "hanuman_25", number: 25, suit: .moksha, deityID: .hanuman, nameEN: "Panchamukhi", nameZH: "五面圣相", nameHI: "पंचमुखी", meaningEN: "Transcending All Forms", meaningZH: "超越万相", meaningHI: "सभी रूपों से परे", descEN: "Hanuman reveals his five-faced, ten-armed cosmic form, shaking all ten directions.", descZH: "哈努曼显现五面十臂宇宙法相威震十方世界", descHI: "हनुमान अपना पंचमुखी, दस भुजाओं वाला विराट रूप प्रकट करते हैं, दसों दिशाओं को कंपित करते हैं"),
        DivinationCard(id: "hanuman_26", number: 26, suit: .moksha, deityID: .hanuman, nameEN: "Chiranjeevi", nameZH: "永生不灭", nameHI: "चिरंजीवी", meaningEN: "Beyond Life and Death", meaningZH: "超脱生死", meaningHI: "जीवन-मृत्यु से परे", descEN: "Hanuman sits atop Mount Meru radiating golden light, immortal and imperishable.", descZH: "哈努曼端坐须弥山巅身放金光永恒不朽", descHI: "हनुमान सुमेरु पर्वत पर विराजमान हैं स्वर्णिम प्रकाश विकीर्ण करते हुए, अमर और अविनाशी"),
        DivinationCard(id: "hanuman_27", number: 27, suit: .moksha, deityID: .hanuman, nameEN: "Vishwarupa", nameZH: "宇宙法身", nameHI: "विश्वरूप", meaningEN: "All Becomes One", meaningZH: "万法归一", meaningHI: "सब एक हो जाता है", descEN: "Hanuman manifests his boundless cosmic body, stars, sun and moon orbiting around him.", descZH: "哈努曼化现无边巨身星辰日月绕其周身运转", descHI: "हनुमान अपना असीम विराट शरीर प्रकट करते हैं, तारे, सूर्य और चंद्रमा उनके चारों ओर परिक्रमा करते हैं"),
        DivinationCard(id: "hanuman_28", number: 28, suit: .moksha, deityID: .hanuman, nameEN: "Vayu Putra", nameZH: "风息归元", nameHI: "वायु पुत्र", meaningEN: "Breath Returns to Source", meaningZH: "气通法界", meaningHI: "श्वास मूल में लौटती है", descEN: "Hanuman controls his breath atop the Himalayas, inhaling and exhaling as one with heaven and earth.", descZH: "哈努曼于喜马拉雅之巅调息吐纳与天地合一", descHI: "हनुमान हिमालय की चोटी पर प्राणायाम करते हैं, स्वर्ग और पृथ्वी के साथ एकाकार"),
        DivinationCard(id: "hanuman_29", number: 29, suit: .moksha, deityID: .hanuman, nameEN: "Rudra Avatar", nameZH: "鲁德罗化身", nameHI: "रुद्र अवतार", meaningEN: "Destruction Reveals Truth", meaningZH: "破灭归真", meaningHI: "विनाश से सत्य प्रकट", descEN: "Hanuman appears as Shiva's avatar, the third eye opening to burn away all ignorance.", descZH: "哈努曼现湿婆化身第三目开启焚尽无明烦恼", descHI: "हनुमान शिव के अवतार रूप में प्रकट होते हैं, तीसरा नेत्र खुलकर सभी अज्ञान को भस्म करता है"),
        DivinationCard(id: "hanuman_30", number: 30, suit: .moksha, deityID: .hanuman, nameEN: "Gyaan Mudra", nameZH: "智慧手印", nameHI: "ज्ञान मुद्रा", meaningEN: "Seeing One's True Nature", meaningZH: "明心见性", meaningHI: "स्वरूप दर्शन", descEN: "Hanuman forms the wisdom mudra, a thousand-petaled lotus crowning his head with light.", descZH: "哈努曼结智慧手印头顶千瓣莲花灌顶光明", descHI: "हनुमान ज्ञान मुद्रा धारण करते हैं, सहस्र दल कमल उनके शीर्ष पर प्रकाश से अभिषेक करता है"),
        DivinationCard(id: "hanuman_31", number: 31, suit: .moksha, deityID: .hanuman, nameEN: "Rama Aikya", nameZH: "融入罗摩", nameHI: "राम ऐक्य", meaningEN: "Merging with the Divine", meaningZH: "主仆不二", meaningHI: "ईश्वर में विलय", descEN: "Hanuman's form dissolves into radiance, merging into Rama's golden divine body as one.", descZH: "哈努曼身形化为光芒融入罗摩金色法身合一", descHI: "हनुमान का रूप प्रकाश में विलीन होता है, राम के स्वर्णिम दिव्य शरीर में एकाकार"),
        DivinationCard(id: "hanuman_32", number: 32, suit: .moksha, deityID: .hanuman, nameEN: "Param Mukti", nameZH: "究竟解脱", nameHI: "परम मुक्ति", meaningEN: "Ultimate Liberation", meaningZH: "圆满自在", meaningHI: "परम मुक्ति", descEN: "Hanuman smiles serenely beneath the Bodhi tree, all bonds released, light pervading everywhere.", descZH: "哈努曼于菩提树下微笑寂照万缘放下光明遍照", descHI: "हनुमान बोधि वृक्ष के नीचे शांत मुस्कान से बैठे हैं, सभी बंधन मुक्त, प्रकाश सर्वत्र व्याप्त"),
    ]
}
