import Foundation

extension DivinationCard {
    static let krishnaCards: [DivinationCard] = [
        DivinationCard(id: "krishna_1", number: 1, suit: .dharma, deityID: .krishna, nameEN: "Gita Updesh", nameZH: "吉塔教诲", nameHI: "गीता उपदेश", meaningEN: "Eternal Dharma Teaching", meaningZH: "正法之言", meaningHI: "शाश्वत धर्म शिक्षा", descEN: "Krishna stands upon the chariot, holding scriptures and proclaiming the eternal dharma to Arjuna.", descZH: "黑天立于战车之上手持经卷向阿周那宣说永恒正法", descHI: "कृष्ण रथ पर खड़े होकर अर्जुन को शाश्वत धर्म का उपदेश देते हैं"),
        DivinationCard(id: "krishna_2", number: 2, suit: .dharma, deityID: .krishna, nameEN: "Dharma Rath", nameZH: "法性战车", nameHI: "धर्म रथ", meaningEN: "Guided by Righteousness", meaningZH: "正道引领", meaningHI: "धर्म द्वारा मार्गदर्शन", descEN: "Krishna holds the reins and drives the chariot, its wheels crushing the path of delusion toward justice.", descZH: "黑天执缰驾御战车车轮碾过迷妄之路驶向正义", descHI: "कृष्ण लगाम थामकर रथ चलाते हैं, पहिये भ्रम का मार्ग कुचलते हुए न्याय की ओर बढ़ते हैं"),
        DivinationCard(id: "krishna_3", number: 3, suit: .dharma, deityID: .krishna, nameEN: "Govardhan", nameZH: "哥瓦尔丹", nameHI: "गोवर्धन", meaningEN: "Protecting Through Dharma", meaningZH: "护法之山", meaningHI: "धर्म से रक्षा", descEN: "Krishna lifts the great mountain with his little finger, sheltering the cowherds from the torrential storm.", descZH: "黑天以小指举起巨山庇护牧民免受暴雨侵袭", descHI: "कृष्ण छोटी उंगली से विशाल पर्वत उठाते हैं, गोपालकों को भीषण तूफान से बचाते हैं"),
        DivinationCard(id: "krishna_4", number: 4, suit: .dharma, deityID: .krishna, nameEN: "Draupadi Vastra", nameZH: "天衣护法", nameHI: "द्रौपदी वस्त्र", meaningEN: "Guarding Dignity", meaningZH: "守护尊严", meaningHI: "गरिमा की रक्षा", descEN: "Krishna creates endless saris to protect Draupadi — the power of dharma cannot be humiliated.", descZH: "黑天化无尽纱丽护德罗波蒂正法之力不可侮", descHI: "कृष्ण द्रौपदी की रक्षा के लिए अनंत साड़ी प्रकट करते हैं — धर्म की शक्ति अपमानित नहीं हो सकती"),
        DivinationCard(id: "krishna_5", number: 5, suit: .dharma, deityID: .krishna, nameEN: "Shankha Naad", nameZH: "法螺之音", nameHI: "शंख नाद", meaningEN: "Dharma Proclaimed", meaningZH: "法音宣告", meaningHI: "धर्म की घोषणा", descEN: "Krishna blows the Panchajanya conch, the sound of righteousness reverberating across Kurukshetra.", descZH: "黑天吹响般遮迦耶法螺正义之声响彻俱卢之野", descHI: "कृष्ण पांचजन्य शंख बजाते हैं, धर्म की ध्वनि कुरुक्षेत्र में गूंजती है"),
        DivinationCard(id: "krishna_6", number: 6, suit: .dharma, deityID: .krishna, nameEN: "Matsya Nyaya", nameZH: "鱼法之诫", nameHI: "मत्स्य न्याय", meaningEN: "Responsibility of Order", meaningZH: "秩序之责", meaningHI: "व्यवस्था का दायित्व", descEN: "Krishna sits on a lotus expounding the duty of all beings — the great fish must not devour the small.", descZH: "黑天端坐莲台阐说众生之责大鱼不可吞小鱼", descHI: "कृष्ण कमल पर बैठकर सभी प्राणियों के कर्तव्य का वर्णन करते हैं — बड़ी मछली छोटी को नहीं निगल सकती"),
        DivinationCard(id: "krishna_7", number: 7, suit: .dharma, deityID: .krishna, nameEN: "Kshetra Dharma", nameZH: "本分之道", nameHI: "क्षेत्र धर्म", meaningEN: "Each to Their Own Path", meaningZH: "各安其法", meaningHI: "सबका अपना मार्ग", descEN: "Krishna reveals beneath the Bodhi tree the divine vision of four varnas each following their destined path.", descZH: "黑天于菩提树下示现四姓各循其道之天命图景", descHI: "कृष्ण बोधि वृक्ष के नीचे चार वर्णों के अपने-अपने मार्ग पर चलने का दिव्य दृश्य दिखाते हैं"),
        DivinationCard(id: "krishna_8", number: 8, suit: .dharma, deityID: .krishna, nameEN: "Satya Vachan", nameZH: "真言之誓", nameHI: "सत्य वचन", meaningEN: "Truth Is Foundation", meaningZH: "真实不虚", meaningHI: "सत्य ही आधार", descEN: "Krishna stands before the sacred fire, his golden words declaring truth as the root of dharma.", descZH: "黑天立于圣火之前金口宣说真实为法之根基", descHI: "कृष्ण पवित्र अग्नि के सामने खड़े हैं, स्वर्ण वाणी से सत्य को धर्म का मूल घोषित करते हैं"),

        DivinationCard(id: "krishna_9", number: 9, suit: .karma, deityID: .krishna, nameEN: "Karma Yoga", nameZH: "行动瑜伽", nameHI: "कर्म योग", meaningEN: "Act Without Attachment", meaningZH: "无执而行", meaningHI: "आसक्ति रहित कर्म", descEN: "Krishna forms a mudra revealing the mystery of acting without attachment to results.", descZH: "黑天双手结印示现不执果报而专注行动之奥义", descHI: "कृष्ण मुद्रा बनाकर फल की आसक्ति के बिना कर्म करने का रहस्य प्रकट करते हैं"),
        DivinationCard(id: "krishna_10", number: 10, suit: .karma, deityID: .krishna, nameEN: "Sudarshana", nameZH: "善见神轮", nameHI: "सुदर्शन", meaningEN: "Wheel of Karma", meaningZH: "业力之轮", meaningHI: "कर्म चक्र", descEN: "Krishna spins the flaming discus on his fingertip, karma cycling endlessly without pause.", descZH: "黑天食指旋转烈焰法轮因果业力周而复始不停息", descHI: "कृष्ण उंगली पर ज्वलंत चक्र घुमाते हैं, कर्म अनंत रूप से बिना रुके चक्रित होता है"),
        DivinationCard(id: "krishna_11", number: 11, suit: .karma, deityID: .krishna, nameEN: "Kurukshetra", nameZH: "俱卢之战", nameHI: "कुरुक्षेत्र", meaningEN: "Field of Decision", meaningZH: "抉择之野", meaningHI: "निर्णय का क्षेत्र", descEN: "Krishna and Arjuna stand together on the battlefield, two armies facing each other, destiny already sealed.", descZH: "黑天与阿周那并立战场两军对峙间命运已然注定", descHI: "कृष्ण और अर्जुन युद्धभूमि पर साथ खड़े हैं, दो सेनाएं आमने-सामने, भाग्य पहले से तय"),
        DivinationCard(id: "krishna_12", number: 12, suit: .karma, deityID: .krishna, nameEN: "Makhan Chor", nameZH: "偷酥油者", nameHI: "माखन चोर", meaningEN: "Playful Actions Bear Fruit", meaningZH: "稚行有果", meaningHI: "चंचल कर्मों का फल", descEN: "Baby Krishna climbs up to steal the butter pot, planting the seeds of joy in mischief.", descZH: "幼年黑天攀爬偷取酥油坛嬉笑中种下欢喜之因", descHI: "बालक कृष्ण मक्खन का मटका चुराने चढ़ते हैं, शरारत में आनंद के बीज बोते हैं"),
        DivinationCard(id: "krishna_13", number: 13, suit: .karma, deityID: .krishna, nameEN: "Seva Marga", nameZH: "奉献之路", nameHI: "सेवा मार्ग", meaningEN: "Service as Offering", meaningZH: "行即供养", meaningHI: "सेवा ही अर्पण", descEN: "Krishna walks barefoot through the cowherding fields, each step an offering of selfless service.", descZH: "黑天赤足行走于牧牛之野每一步皆为无私之奉献", descHI: "कृष्ण गोचारण भूमि में नंगे पैर चलते हैं, हर कदम निःस्वार्थ सेवा का अर्पण"),
        DivinationCard(id: "krishna_14", number: 14, suit: .karma, deityID: .krishna, nameEN: "Sudama Bhakti", nameZH: "苏达摩之献", nameHI: "सुदामा भक्ति", meaningEN: "Small Cause, Great Effect", meaningZH: "微因大果", meaningHI: "छोटा कारण, बड़ा प्रभाव", descEN: "Poor friend Sudama offers a handful of beaten rice; Krishna returns with boundless grace.", descZH: "贫友苏达摩献上一捧扁米黑天回赐以无尽恩泽", descHI: "गरीब मित्र सुदामा मुट्ठी भर चावल अर्पित करते हैं; कृष्ण असीम कृपा से उत्तर देते हैं"),
        DivinationCard(id: "krishna_15", number: 15, suit: .karma, deityID: .krishna, nameEN: "Rann Bhoomi", nameZH: "业战之场", nameHI: "रण भूमि", meaningEN: "Karma Manifests", meaningZH: "果报现前", meaningHI: "कर्मफल प्रकट", descEN: "Arrows rain down upon Kurukshetra, the good and evil karma sown in the past now manifesting one by one.", descZH: "俱卢之野箭如雨下往昔所造善恶之业一一兑现", descHI: "कुरुक्षेत्र पर बाणों की वर्षा होती है, अतीत में बोए गए अच्छे-बुरे कर्म एक-एक कर प्रकट होते हैं"),
        DivinationCard(id: "krishna_16", number: 16, suit: .karma, deityID: .krishna, nameEN: "Chakra Vyuha", nameZH: "法阵之困", nameHI: "चक्र व्यूह", meaningEN: "Trapped by Own Karma", meaningZH: "业网缠缚", meaningHI: "अपने कर्मों में फंसना", descEN: "The battle formation spirals like a labyrinth, beings trapped within the web of their own karma.", descZH: "战阵层层旋转如迷宫众生困于自造之业力罗网", descHI: "युद्ध व्यूह भूलभुलैया की तरह घूमता है, प्राणी अपने कर्मों के जाल में फंसे हैं"),

        DivinationCard(id: "krishna_17", number: 17, suit: .kama, deityID: .krishna, nameEN: "Radha-Krishna", nameZH: "拉达与黑天", nameHI: "राधा-कृष्ण", meaningEN: "Sacred Divine Love", meaningZH: "神圣之爱", meaningHI: "पवित्र दिव्य प्रेम", descEN: "Radha and Krishna embrace under the moonlight, divine love transcending all worldly bonds.", descZH: "拉达与黑天于月光下相拥神性之爱超越一切世间情", descHI: "राधा और कृष्ण चांदनी में आलिंगन करते हैं, दिव्य प्रेम सभी सांसारिक बंधनों से परे"),
        DivinationCard(id: "krishna_18", number: 18, suit: .kama, deityID: .krishna, nameEN: "Murali", nameZH: "神笛牧歌", nameHI: "मुरली", meaningEN: "Soul's Calling", meaningZH: "心灵召唤", meaningHI: "आत्मा की पुकार", descEN: "Krishna leans against the Kadamba tree playing his flute, the melody piercing all things and awakening the soul.", descZH: "黑天倚于迦昙波树下吹笛笛音穿透万物唤醒灵魂", descHI: "कृष्ण कदम्ब वृक्ष के सहारे बांसुरी बजाते हैं, धुन सब कुछ भेदकर आत्मा को जगाती है"),
        DivinationCard(id: "krishna_19", number: 19, suit: .kama, deityID: .krishna, nameEN: "Raas Leela", nameZH: "月下圆舞", nameHI: "रास लीला", meaningEN: "Ecstasy of Divine Love", meaningZH: "爱之狂喜", meaningHI: "दिव्य प्रेम का उल्लास", descEN: "On a full moon night Krishna multiplies himself to dance with every gopi by the Yamuna.", descZH: "满月之夜黑天化万身与牧女共舞于耶穆纳河畔", descHI: "पूर्णिमा की रात कृष्ण यमुना तट पर हर गोपी के साथ नृत्य करने स्वयं को बहुगुणित करते हैं"),
        DivinationCard(id: "krishna_20", number: 20, suit: .kama, deityID: .krishna, nameEN: "Yamuna Teer", nameZH: "耶穆纳河畔", nameHI: "यमुना तीर", meaningEN: "Longing Waters", meaningZH: "渴慕之水", meaningHI: "विरह का जल", descEN: "Krishna stands by the sacred river, the blue waters reflecting his peacock feather and infinite tenderness.", descZH: "黑天立于圣河之畔碧水倒映孔雀翎与无尽柔情", descHI: "कृष्ण पवित्र नदी के किनारे खड़े हैं, नीला जल उनके मोर पंख और अनंत कोमलता को प्रतिबिंबित करता है"),
        DivinationCard(id: "krishna_21", number: 21, suit: .kama, deityID: .krishna, nameEN: "Vrindavan Lila", nameZH: "温达文神游", nameHI: "वृंदावन लीला", meaningEN: "Sacred Garden of Love", meaningZH: "爱之圣境", meaningHI: "प्रेम का पवित्र उद्यान", descEN: "Krishna strolls through the sacred forest of Vrindavan, flowers blooming everywhere — all things born from love.", descZH: "黑天漫步于温达文圣林花开遍野万物皆因爱而生", descHI: "कृष्ण वृंदावन के पवित्र वन में विचरण करते हैं, चारों ओर फूल खिले — सब कुछ प्रेम से उत्पन्न"),
        DivinationCard(id: "krishna_22", number: 22, suit: .kama, deityID: .krishna, nameEN: "Meera Bhav", nameZH: "弥罗之心", nameHI: "मीरा भाव", meaningEN: "Love Without Regret", meaningZH: "痴爱无悔", meaningHI: "बिना पछतावे का प्रेम", descEN: "Meera sings with tears, the cup of poison transforming into nectar offered at Krishna's feet.", descZH: "弥罗含泪歌唱将毒酒化为甘露献于黑天足下", descHI: "मीरा आंसुओं के साथ गाती हैं, विष का प्याला अमृत बनकर कृष्ण के चरणों में अर्पित होता है"),
        DivinationCard(id: "krishna_23", number: 23, suit: .kama, deityID: .krishna, nameEN: "Gopi Prem", nameZH: "牧女之爱", nameHI: "गोपी प्रेम", meaningEN: "Many Hearts, One Love", meaningZH: "众心归一", meaningHI: "अनेक हृदय, एक प्रेम", descEN: "The gopis each carry lamps rushing toward the flute's sound, a thousand loves converging into one.", descZH: "众牧女各捧灯火奔向笛声万千爱慕汇聚于一", descHI: "गोपियां दीप लेकर बांसुरी की ध्वनि की ओर दौड़ती हैं, हजारों प्रेम एक में एकत्र होते हैं"),
        DivinationCard(id: "krishna_24", number: 24, suit: .kama, deityID: .krishna, nameEN: "Mor Mukut", nameZH: "孔雀翎冠", nameHI: "मोर मुकुट", meaningEN: "Mark of Divine Beauty", meaningZH: "爱之印记", meaningHI: "दिव्य सौंदर्य का चिह्न", descEN: "The peacock feather sways in Krishna's hair with the wind, beauty incarnate captivating all creation.", descZH: "黑天发间孔雀翎羽随风而动美之化身令万物倾慕", descHI: "कृष्ण के बालों में मोर पंख हवा से लहराता है, सौंदर्य का अवतार सृष्टि को मोहित करता है"),

        DivinationCard(id: "krishna_25", number: 25, suit: .moksha, deityID: .krishna, nameEN: "Vishwarupa", nameZH: "宇宙神显", nameHI: "विश्वरूप", meaningEN: "All Forms in One", meaningZH: "万相归一", meaningHI: "सभी रूप एक में", descEN: "Krishna reveals his infinite cosmic body, a thousand suns shining at once, all realms within one form.", descZH: "黑天示现无限宇宙之身千日并照万界于一身显现", descHI: "कृष्ण अपना अनंत विराट शरीर प्रकट करते हैं, एक साथ हजार सूर्य चमकते हैं, सभी लोक एक रूप में"),
        DivinationCard(id: "krishna_26", number: 26, suit: .moksha, deityID: .krishna, nameEN: "Atma Jnana", nameZH: "真我之智", nameHI: "आत्म ज्ञान", meaningEN: "Spiritual Awakening", meaningZH: "灵性觉醒", meaningHI: "आध्यात्मिक जागृति", descEN: "Krishna sits in the cosmic void, golden light radiating from his chest, piercing the darkness of ignorance.", descZH: "黑天端坐虚空之中胸口放射金光照破无明黑暗", descHI: "कृष्ण ब्रह्मांडीय शून्य में बैठे हैं, वक्ष से स्वर्ण प्रकाश अज्ञान के अंधकार को भेदता है"),
        DivinationCard(id: "krishna_27", number: 27, suit: .moksha, deityID: .krishna, nameEN: "Paramatma", nameZH: "超灵遍在", nameHI: "परमात्मा", meaningEN: "Divine in Every Being", meaningZH: "遍满一切", meaningHI: "हर प्राणी में ईश्वर", descEN: "Krishna becomes a tiny light dwelling within the heart-lotus of every being, never apart.", descZH: "黑天化为微光住于每一众生心莲之中永不分离", descHI: "कृष्ण सूक्ष्म प्रकाश बनकर हर प्राणी के हृदय कमल में निवास करते हैं, कभी अलग नहीं"),
        DivinationCard(id: "krishna_28", number: 28, suit: .moksha, deityID: .krishna, nameEN: "Om Namo", nameZH: "唵之回响", nameHI: "ॐ नमो", meaningEN: "Source Sound", meaningZH: "本源之音", meaningHI: "मूल ध्वनि", descEN: "Krishna forms the meditation mudra in cosmic space, golden Om expanding outward from the heart chakra.", descZH: "黑天于宇宙虚空中结定印唵字金光自心轮向外扩散", descHI: "कृष्ण ब्रह्मांडीय अंतरिक्ष में ध्यान मुद्रा बनाते हैं, स्वर्ण ॐ हृदय चक्र से बाहर फैलता है"),
        DivinationCard(id: "krishna_29", number: 29, suit: .moksha, deityID: .krishna, nameEN: "Ananta Shesha", nameZH: "无尽蛇眠", nameHI: "अनंत शेष", meaningEN: "Beyond the Cycle", meaningZH: "超越轮回", meaningHI: "चक्र से परे", descEN: "Krishna reclines upon the thousand-headed serpent, the milk ocean calm, all phenomena returning to truth.", descZH: "黑天安卧于千头巨蛇之上乳海波平万象寂灭归真", descHI: "कृष्ण सहस्र मस्तक वाले शेषनाग पर लेटे हैं, क्षीर सागर शांत, सभी घटनाएं सत्य में लौटती हैं"),
        DivinationCard(id: "krishna_30", number: 30, suit: .moksha, deityID: .krishna, nameEN: "Moksha Dwar", nameZH: "解脱之门", nameHI: "मोक्ष द्वार", meaningEN: "Gate of Ultimate Freedom", meaningZH: "终极自由", meaningHI: "परम मुक्ति का द्वार", descEN: "Golden lotus gates slowly open, Krishna stands within extending his compassionate hand to all beings.", descZH: "金色莲门徐徐开启黑天立于门中向众生伸出慈手", descHI: "स्वर्ण कमल द्वार धीरे-धीरे खुलते हैं, कृष्ण भीतर खड़े होकर सभी प्राणियों की ओर करुणामय हाथ बढ़ाते हैं"),
        DivinationCard(id: "krishna_31", number: 31, suit: .moksha, deityID: .krishna, nameEN: "Leela Samapti", nameZH: "神游终归", nameHI: "लीला समाप्ति", meaningEN: "Divine Play Concludes", meaningZH: "放下幻戏", meaningHI: "दिव्य लीला का अंत", descEN: "Krishna smiles and waves farewell, the world's myriad phenomena rolling up like a curtain into silence.", descZH: "黑天微笑挥手世间万象如幕布般卷起归于寂静", descHI: "कृष्ण मुस्कुराते हुए विदा करते हैं, संसार की सभी घटनाएं पर्दे की तरह सिमटकर मौन में लौटती हैं"),
        DivinationCard(id: "krishna_32", number: 32, suit: .moksha, deityID: .krishna, nameEN: "Purna Avatar", nameZH: "圆满化身", nameHI: "पूर्ण अवतार", meaningEN: "Complete Perfection", meaningZH: "究竟圆满", meaningHI: "पूर्ण सिद्धि", descEN: "Krishna stands upon the thousand-petaled golden lotus, light pervading all three worlds, everything returning to perfection.", descZH: "黑天立于千瓣金莲之上光明遍照三界一切终归圆满", descHI: "कृष्ण सहस्र दल स्वर्ण कमल पर खड़े हैं, प्रकाश तीनों लोकों में व्याप्त, सब कुछ पूर्णता में लौटता है"),
    ]
}
