import Foundation

extension DivinationCard {
    static let lakshmiCards: [DivinationCard] = [
        DivinationCard(id: "lakshmi_1", number: 1, suit: .dharma, deityID: .lakshmi, nameEN: "Padma", nameZH: "莲华", nameHI: "पद्म", meaningEN: "Pure Inner Nature", meaningZH: "清净自性", meaningHI: "शुद्ध आंतरिक स्वभाव", descEN: "A golden lotus blooms from the mud, petals dripping with nectar and pure light.", descZH: "金莲自淤泥中盛放，花瓣滴落甘露清光", descHI: "कीचड़ से स्वर्ण कमल खिलता है, पंखुड़ियों से अमृत और शुद्ध प्रकाश टपकता है"),
        DivinationCard(id: "lakshmi_2", number: 2, suit: .dharma, deityID: .lakshmi, nameEN: "Dharma Lakshmi", nameZH: "法性天母", nameHI: "धर्म लक्ष्मी", meaningEN: "Upholding Cosmic Law", meaningZH: "正法持世", meaningHI: "ब्रह्मांडीय नियम का पालन", descEN: "The goddess holds a dharma wheel and scriptures, seated on a lotus proclaiming the righteous path.", descZH: "女神手持法轮经卷，端坐莲台宣示正道", descHI: "देवी धर्म चक्र और शास्त्र धारण किए कमल पर विराजमान, धर्म मार्ग की घोषणा करती हैं"),
        DivinationCard(id: "lakshmi_3", number: 3, suit: .dharma, deityID: .lakshmi, nameEN: "Satya", nameZH: "真谛", nameHI: "सत्य", meaningEN: "Truth as Treasure", meaningZH: "诚实法宝", meaningHI: "सत्य ही धन", descEN: "The goddess holds a flame in both hands, truthful words transforming into golden Sanskrit.", descZH: "女神双手捧持光焰，真言化作金色梵文", descHI: "देवी दोनों हाथों में ज्योति धारण करती हैं, सत्य वचन स्वर्ण संस्कृत में रूपांतरित होते हैं"),
        DivinationCard(id: "lakshmi_4", number: 4, suit: .dharma, deityID: .lakshmi, nameEN: "Shanti", nameZH: "寂静", nameHI: "शांति", meaningEN: "Patient Mindfulness", meaningZH: "安忍正念", meaningHI: "धैर्यपूर्ण सजगता", descEN: "The goddess meditates in still moonlit waters, white lotuses surrounding her like mirrors.", descZH: "女神于月下静水中禅坐，白莲环绕如镜", descHI: "देवी शांत चांदनी जल में ध्यान करती हैं, श्वेत कमल दर्पण की तरह उन्हें घेरे हुए"),
        DivinationCard(id: "lakshmi_5", number: 5, suit: .dharma, deityID: .lakshmi, nameEN: "Daya", nameZH: "慈悲", nameHI: "दया", meaningEN: "Compassion for All", meaningZH: "悲悯万灵", meaningHI: "सबके लिए करुणा", descEN: "The goddess bends down to sprinkle nectar upon the suffering beings of the earth.", descZH: "女神俯身以甘露洒向苦难众生大地", descHI: "देवी झुककर पृथ्वी के कष्टपीड़ित प्राणियों पर अमृत छिड़कती हैं"),
        DivinationCard(id: "lakshmi_6", number: 6, suit: .dharma, deityID: .lakshmi, nameEN: "Rita", nameZH: "天则", nameHI: "ऋत", meaningEN: "Universal Law", meaningZH: "宇宙恒律", meaningHI: "सार्वभौमिक नियम", descEN: "The goddess stands within the cosmic wheel, sun and moon orbiting in their eternal order.", descZH: "女神立于星轮之中，日月依序环绕运转", descHI: "देवी ब्रह्मांडीय चक्र में खड़ी हैं, सूर्य और चंद्रमा अपने शाश्वत क्रम में परिक्रमा करते हैं"),
        DivinationCard(id: "lakshmi_7", number: 7, suit: .dharma, deityID: .lakshmi, nameEN: "Mangala", nameZH: "吉祥", nameHI: "मंगल", meaningEN: "Auspicious Virtue", meaningZH: "德行瑞应", meaningHI: "शुभ गुण", descEN: "The red-robed goddess treads upon auspicious knots, auspicious clouds and good omens rising from all directions.", descZH: "红衣女神足踏吉祥结，八方涌现祥云瑞兆", descHI: "लाल वस्त्रधारी देवी शुभ गांठों पर चलती हैं, सभी दिशाओं से शुभ बादल और मंगल चिह्न उठते हैं"),
        DivinationCard(id: "lakshmi_8", number: 8, suit: .dharma, deityID: .lakshmi, nameEN: "Seva", nameZH: "奉献", nameHI: "सेवा", meaningEN: "Selfless Giving", meaningZH: "无私布施", meaningHI: "निःस्वार्थ दान", descEN: "The goddess manifests a thousand hands giving in all directions, golden light showering the world.", descZH: "女神化千手向四方施赠，金光遍洒人间", descHI: "देवी सहस्र भुजाएं प्रकट कर सभी दिशाओं में दान करती हैं, स्वर्ण प्रकाश संसार पर बरसता है"),

        DivinationCard(id: "lakshmi_9", number: 9, suit: .karma, deityID: .lakshmi, nameEN: "Dhana", nameZH: "财宝", nameHI: "धन", meaningEN: "Diligence Brings Abundance", meaningZH: "勤作丰源", meaningHI: "परिश्रम प्रचुरता लाता है", descEN: "Gold coins cascade like a waterfall from the goddess's palms into a treasure lotus pool.", descZH: "金币自女神掌中如瀑倾泻入聚宝莲池", descHI: "देवी की हथेलियों से स्वर्ण सिक्के जलप्रपात की तरह खजाना कमल सरोवर में गिरते हैं"),
        DivinationCard(id: "lakshmi_10", number: 10, suit: .karma, deityID: .lakshmi, nameEN: "Dhanya", nameZH: "丰收", nameHI: "धान्य", meaningEN: "Reaping What You Sow", meaningZH: "耕耘善果", meaningHI: "जो बोया वो काटा", descEN: "The goddess embraces golden grain stalks, fields of wheat rolling with abundant harvest.", descZH: "女神怀抱金色稻穗，田野麦浪翻涌丰盈", descHI: "देवी स्वर्ण धान की बालियां गले लगाती हैं, खेतों में गेहूं की लहरें प्रचुर फसल से लहलहाती हैं"),
        DivinationCard(id: "lakshmi_11", number: 11, suit: .karma, deityID: .lakshmi, nameEN: "Veera", nameZH: "勇健", nameHI: "वीर", meaningEN: "Courageous Effort", meaningZH: "精进破障", meaningHI: "साहसी प्रयास", descEN: "The goddess wears armor and holds a sword, standing fearlessly upon a lotus.", descZH: "女神身披战甲手持宝剑，脚踏莲花无畏", descHI: "देवी कवच पहने तलवार धारण किए कमल पर निडर खड़ी हैं"),
        DivinationCard(id: "lakshmi_12", number: 12, suit: .karma, deityID: .lakshmi, nameEN: "Punya", nameZH: "功德", nameHI: "पुण्य", meaningEN: "Good Karma, Good Fortune", meaningZH: "善因善缘", meaningHI: "शुभ कर्म, शुभ भाग्य", descEN: "Behind the goddess stands the tree of cause and effect, lush with leaves and heavy with fruit.", descZH: "女神身后因果之树枝繁叶茂果实累累", descHI: "देवी के पीछे कारण-प्रभाव का वृक्ष खड़ा है, हरी-भरी पत्तियों और फलों से लदा हुआ"),
        DivinationCard(id: "lakshmi_13", number: 13, suit: .karma, deityID: .lakshmi, nameEN: "Karya", nameZH: "事业", nameHI: "कार्य", meaningEN: "Right Work Leads the Way", meaningZH: "正业成道", meaningHI: "सत्कर्म से मार्ग", descEN: "The goddess forges with a golden hammer, sparks transforming into a sky full of stars.", descZH: "女神手执金杵锻造，火花化作漫天繁星", descHI: "देवी स्वर्ण हथौड़े से गढ़ती हैं, चिंगारियां आकाश भर के तारों में बदल जाती हैं"),
        DivinationCard(id: "lakshmi_14", number: 14, suit: .karma, deityID: .lakshmi, nameEN: "Phala", nameZH: "果报", nameHI: "फल", meaningEN: "Cause and Effect Are True", meaningZH: "因果不虚", meaningHI: "कारण और प्रभाव सत्य हैं", descEN: "The goddess holds scales to weigh good and evil, lotus petals drifting to both sides.", descZH: "女神持天秤称量善恶，莲瓣纷落两端", descHI: "देवी तराजू से अच्छाई और बुराई तौलती हैं, कमल पंखुड़ियां दोनों तरफ गिरती हैं"),
        DivinationCard(id: "lakshmi_15", number: 15, suit: .karma, deityID: .lakshmi, nameEN: "Tapas", nameZH: "苦行", nameHI: "तपस", meaningEN: "Perseverance Through Fire", meaningZH: "炼行定力", meaningHI: "अग्नि से तपस्या", descEN: "The goddess sits unmoved within blazing flames, radiating cool and serene light.", descZH: "女神于烈焰中端坐不动，身放清凉光芒", descHI: "देवी भीषण अग्नि में अविचलित बैठी हैं, शीतल और शांत प्रकाश विकीर्ण करती हैं"),
        DivinationCard(id: "lakshmi_16", number: 16, suit: .karma, deityID: .lakshmi, nameEN: "Abhyasa", nameZH: "修习", nameHI: "अभ्यास", meaningEN: "Daily Practice Builds Success", meaningZH: "日积功成", meaningHI: "दैनिक अभ्यास से सफलता", descEN: "The goddess climbs golden stairs step by step, a lotus blooming on each stair.", descZH: "女神逐级登上金色阶梯，每阶绽放一朵莲", descHI: "देवी कदम-कदम स्वर्ण सीढ़ियां चढ़ती हैं, हर सीढ़ी पर एक कमल खिलता है"),

        DivinationCard(id: "lakshmi_17", number: 17, suit: .kama, deityID: .lakshmi, nameEN: "Santana", nameZH: "传承", nameHI: "संतान", meaningEN: "Family Fulfillment", meaningZH: "眷属圆满", meaningHI: "पारिवारिक पूर्णता", descEN: "The goddess cradles an infant, children surrounding her in joyful laughter.", descZH: "女神怀中抱持婴孩，周围儿女环绕欢笑", descHI: "देवी शिशु को गोद में लिए हैं, बच्चे उनके चारों ओर हंसी-खुशी से घिरे हैं"),
        DivinationCard(id: "lakshmi_18", number: 18, suit: .kama, deityID: .lakshmi, nameEN: "Prema", nameZH: "爱慕", nameHI: "प्रेम", meaningEN: "Devotional Love Reaches God", meaningZH: "虔爱通神", meaningHI: "भक्ति प्रेम ईश्वर तक", descEN: "Lakshmi and Vishnu lean upon each other, lotus vines intertwining around them.", descZH: "拉克什米与毗湿奴相依，莲花藤蔓缠绕交织", descHI: "लक्ष्मी और विष्णु एक-दूसरे पर टिके हैं, कमल की लताएं उनके चारों ओर गुंथी हुई"),
        DivinationCard(id: "lakshmi_19", number: 19, suit: .kama, deityID: .lakshmi, nameEN: "Deepa", nameZH: "灯焰", nameHI: "दीप", meaningEN: "Light of Heart's Desire", meaningZH: "心愿明灯", meaningHI: "हृदय की इच्छा का दीप", descEN: "Ten thousand Diwali oil lamps sparkle brilliantly, the goddess appearing from a sea of light.", descZH: "排灯节万盏油灯璀璨，女神自光海中显现", descHI: "दीपावली के दस हजार दीप जगमगाते हैं, देवी प्रकाश सागर से प्रकट होती हैं"),
        DivinationCard(id: "lakshmi_20", number: 20, suit: .kama, deityID: .lakshmi, nameEN: "Shraddha", nameZH: "信愿", nameHI: "श्रद्धा", meaningEN: "Sincere Faith Answers", meaningZH: "至诚感应", meaningHI: "सच्ची श्रद्धा उत्तर देती है", descEN: "The goddess presses palms together gazing up at the sky, golden light pouring from her heart.", descZH: "女神双手合十仰望苍穹，心口涌出金色光", descHI: "देवी हाथ जोड़कर आकाश की ओर देखती हैं, हृदय से स्वर्ण प्रकाश उमड़ता है"),
        DivinationCard(id: "lakshmi_21", number: 21, suit: .kama, deityID: .lakshmi, nameEN: "Madhura", nameZH: "甘美", nameHI: "मधुर", meaningEN: "Joy of Dharma", meaningZH: "法喜充满", meaningHI: "धर्म का आनंद", descEN: "The goddess pours honey, flower rain drifting down as hundreds of birds arrive.", descZH: "女神手持蜜壶倾洒，花雨纷飞百鸟来朝", descHI: "देवी मधु उंडेलती हैं, पुष्प वर्षा होती है और सैकड़ों पक्षी आते हैं"),
        DivinationCard(id: "lakshmi_22", number: 22, suit: .kama, deityID: .lakshmi, nameEN: "Saubhagya", nameZH: "福缘", nameHI: "सौभाग्य", meaningEN: "Wishes Fulfilled", meaningZH: "宿愿得偿", meaningHI: "इच्छाएं पूर्ण", descEN: "The goddess ties two twin lotuses together with a red thread, both blooming in radiance.", descZH: "女神以红绳系起两朵并蒂莲花绽放", descHI: "देवी लाल धागे से दो जुड़वा कमल बांधती हैं, दोनों दीप्तिमान खिलते हैं"),
        DivinationCard(id: "lakshmi_23", number: 23, suit: .kama, deityID: .lakshmi, nameEN: "Rasa", nameZH: "情味", nameHI: "रस", meaningEN: "Richness of Life", meaningZH: "生命醇味", meaningHI: "जीवन की समृद्धि", descEN: "The goddess dances gracefully in a garden, her flowing garments transforming into a rainbow.", descZH: "女神于花园中翩然起舞，衣袂化作彩虹", descHI: "देवी बगीचे में सुंदर नृत्य करती हैं, उनके लहराते वस्त्र इंद्रधनुष में बदल जाते हैं"),
        DivinationCard(id: "lakshmi_24", number: 24, suit: .kama, deityID: .lakshmi, nameEN: "Harsha", nameZH: "欢喜", nameHI: "हर्ष", meaningEN: "Delight and Bliss", meaningZH: "得乐欢悦", meaningHI: "आनंद और उल्लास", descEN: "The goddess looks up smiling and scattering flowers, a peacock fans its tail as a hundred flowers bloom.", descZH: "女神仰面微笑散花，孔雀开屏百花齐放", descHI: "देवी मुस्कुराते हुए ऊपर देखती हैं और फूल बिखेरती हैं, मोर पंख फैलाता है और सौ फूल खिलते हैं"),

        DivinationCard(id: "lakshmi_25", number: 25, suit: .moksha, deityID: .lakshmi, nameEN: "Ashta Lakshmi", nameZH: "八相圆满", nameHI: "अष्ट लक्ष्मी", meaningEN: "Eight Virtues Complete", meaningZH: "八德具足", meaningHI: "आठ गुण पूर्ण", descEN: "Eight forms of the goddess sit in a lotus formation, great light radiating from the center.", descZH: "八位女神化身环坐成莲形，中央放大光明", descHI: "देवी के आठ रूप कमल आकृति में बैठे हैं, केंद्र से महान प्रकाश विकीर्ण होता है"),
        DivinationCard(id: "lakshmi_26", number: 26, suit: .moksha, deityID: .lakshmi, nameEN: "Gaja", nameZH: "象王", nameHI: "गज", meaningEN: "Majestic Liberation", meaningZH: "威德解脱", meaningHI: "भव्य मुक्ति", descEN: "Two white elephants pour golden urns to consecrate the goddess, lotus rain descending from heaven.", descZH: "双白象以金瓶为女神灌顶，莲雨自天而降", descHI: "दो श्वेत हाथी स्वर्ण कलश से देवी का अभिषेक करते हैं, स्वर्ग से कमल वर्षा होती है"),
        DivinationCard(id: "lakshmi_27", number: 27, suit: .moksha, deityID: .lakshmi, nameEN: "Vidya", nameZH: "明智", nameHI: "विद्या", meaningEN: "Wisdom Pierces Dark", meaningZH: "智慧破暗", meaningHI: "ज्ञान अंधकार भेदता है", descEN: "The goddess holds burning scriptures, every word transforming into light and merging into the void.", descZH: "女神手持燃烧经卷，字字化光融入虚空", descHI: "देवी जलते शास्त्र धारण करती हैं, हर शब्द प्रकाश में बदलकर शून्य में विलीन होता है"),
        DivinationCard(id: "lakshmi_28", number: 28, suit: .moksha, deityID: .lakshmi, nameEN: "Moksha Lakshmi", nameZH: "解脱天母", nameHI: "मोक्ष लक्ष्मी", meaningEN: "Ultimate Freedom", meaningZH: "究竟自在", meaningHI: "परम स्वतंत्रता", descEN: "The goddess transforms into pure light merging into infinite space, the lotus seat gradually fading.", descZH: "女神化为纯光融入无限虚空，莲座渐隐", descHI: "देवी शुद्ध प्रकाश में रूपांतरित होकर अनंत अंतरिक्ष में विलीन होती हैं, कमल आसन धीरे-धीरे लुप्त"),
        DivinationCard(id: "lakshmi_29", number: 29, suit: .moksha, deityID: .lakshmi, nameEN: "Amrita", nameZH: "甘露", nameHI: "अमृत", meaningEN: "Nectar Beyond Death", meaningZH: "不死轮回", meaningHI: "मृत्यु से परे अमृत", descEN: "The goddess lifts a vessel of moonlight nectar, the elixir spilling to dissolve the cycle of birth and death.", descZH: "女神捧起月光甘露瓶，琼浆洒落化解生死", descHI: "देवी चांदनी अमृत पात्र उठाती हैं, अमृत बहकर जन्म-मृत्यु चक्र को विलीन करता है"),
        DivinationCard(id: "lakshmi_30", number: 30, suit: .moksha, deityID: .lakshmi, nameEN: "Ananta", nameZH: "无尽", nameHI: "अनंत", meaningEN: "Infinite Wholeness", meaningZH: "无边圆融", meaningHI: "अनंत पूर्णता", descEN: "The goddess rests upon Vishnu's serpent bed, the cosmic ocean stretching endlessly.", descZH: "女神安住于毗湿奴蛇床之上，宇宙海无尽", descHI: "देवी विष्णु के शेषनाग शय्या पर विश्राम करती हैं, ब्रह्मांडीय सागर अनंत तक फैला है"),
        DivinationCard(id: "lakshmi_31", number: 31, suit: .moksha, deityID: .lakshmi, nameEN: "Svarna", nameZH: "金光", nameHI: "स्वर्ण", meaningEN: "True Golden Nature", meaningZH: "本性纯金", meaningHI: "सच्चा स्वर्ण स्वभाव", descEN: "The goddess's entire being transforms into a body of pure golden light, all things reflected within.", descZH: "女神全身化为纯金光体，万物映照其中", descHI: "देवी का संपूर्ण अस्तित्व शुद्ध स्वर्ण प्रकाश शरीर में रूपांतरित होता है, सभी वस्तुएं उसमें प्रतिबिंबित"),
        DivinationCard(id: "lakshmi_32", number: 32, suit: .moksha, deityID: .lakshmi, nameEN: "Purna", nameZH: "圆成", nameHI: "पूर्ण", meaningEN: "All Is Complete", meaningZH: "一切圆满", meaningHI: "सब पूर्ण है", descEN: "The goddess forms the wish-granting mudra with a smile, the eight-petaled golden lotus closes in perfect completion.", descZH: "女神结施愿印微笑，八瓣金莲圆满合拢", descHI: "देवी मुस्कुराते हुए वरद मुद्रा बनाती हैं, आठ पंखुड़ियों वाला स्वर्ण कमल पूर्ण रूप से बंद होता है"),
    ]
}
