import Foundation

extension DivinationCard {
    static let ramaCards: [DivinationCard] = [
        DivinationCard(id: "rama_1", number: 1, suit: .dharma, deityID: .rama, nameEN: "Kodanda", nameZH: "神弓柯丹达", nameHI: "कोदंड", meaningEN: "Authority of Dharma", meaningZH: "正法之威", meaningHI: "धर्म का अधिकार", descEN: "Rama lifts Shiva's divine bow, the bowstring's vibration echoing between heaven and earth.", descZH: "罗摩举起湿婆神弓，弓弦震响回荡天地之间", descHI: "राम शिव का दिव्य धनुष उठाते हैं, प्रत्यंचा की गूंज स्वर्ग और पृथ्वी के बीच गूंजती है"),
        DivinationCard(id: "rama_2", number: 2, suit: .dharma, deityID: .rama, nameEN: "Maryada", nameZH: "至上法度", nameHI: "मर्यादा", meaningEN: "Upholding Righteousness", meaningZH: "恪守正道", meaningHI: "धर्म का पालन", descEN: "Rama stands before the pillar of dharma, golden light outlining his unwavering form.", descZH: "罗摩端立于王道之柱前，金光勾勒其不动身姿", descHI: "राम धर्म स्तंभ के सामने खड़े हैं, स्वर्ण प्रकाश उनके अडिग रूप की रूपरेखा बनाता है"),
        DivinationCard(id: "rama_3", number: 3, suit: .dharma, deityID: .rama, nameEN: "Pitru Vakya", nameZH: "父命难违", nameHI: "पितृ वाक्य", meaningEN: "Filial Devotion", meaningZH: "孝道承诺", meaningHI: "पितृ भक्ति", descEN: "Rama kneels at his father's feet, palms joined to receive the command of exile.", descZH: "罗摩跪于父王足前，双手合十领受流放之命", descHI: "राम पिता के चरणों में घुटने टेकते हैं, हाथ जोड़कर वनवास का आदेश स्वीकार करते हैं"),
        DivinationCard(id: "rama_4", number: 4, suit: .dharma, deityID: .rama, nameEN: "Lakshmana Rekha", nameZH: "护法结界", nameHI: "लक्ष्मण रेखा", meaningEN: "Sacred Boundary", meaningZH: "守界不越", meaningHI: "पवित्र सीमा", descEN: "A golden line of fire burns upon the ground, an inviolable protective boundary within.", descZH: "地上燃起一道金色光线，结界之内圣火不可侵犯", descHI: "जमीन पर अग्नि की स्वर्ण रेखा जलती है, इसके भीतर अलंघ्य सुरक्षा कवच"),
        DivinationCard(id: "rama_5", number: 5, suit: .dharma, deityID: .rama, nameEN: "Rama Darbar", nameZH: "罗摩圣廷", nameHI: "राम दरबार", meaningEN: "Just Court", meaningZH: "圣廷正义", meaningHI: "न्यायपूर्ण दरबार", descEN: "Rama sits upon his throne, ministers in place, the court filled with solemn radiance.", descZH: "罗摩端坐宝座，众臣归位，殿中光辉庄严肃穆", descHI: "राम सिंहासन पर विराजमान हैं, मंत्री अपने स्थान पर, दरबार गंभीर दीप्ति से भरा है"),
        DivinationCard(id: "rama_6", number: 6, suit: .dharma, deityID: .rama, nameEN: "Vanara Sena", nameZH: "猴军誓盟", nameHI: "वानर सेना", meaningEN: "Alliance of Righteousness", meaningZH: "义军集结", meaningHI: "धर्म का गठबंधन", descEN: "Countless monkey warriors gather beneath Rama's battle banner, wielding trees as weapons.", descZH: "无数猴族战士持树为兵齐聚于罗摩战旗之下", descHI: "अनगिनत वानर योद्धा राम के युद्ध ध्वज तले एकत्र हैं, वृक्षों को हथियार बनाए"),
        DivinationCard(id: "rama_7", number: 7, suit: .dharma, deityID: .rama, nameEN: "Dharma Yuddha", nameZH: "法战", nameHI: "धर्म युद्ध", meaningEN: "Righteous Battle", meaningZH: "以正伐邪", meaningHI: "धर्म युद्ध", descEN: "Rama draws his bow and aims, the arrowhead's light shooting toward Lanka in the darkness.", descZH: "罗摩弯弓搭箭，箭尖光芒射向黑暗中的楞伽城", descHI: "राम धनुष पर बाण चढ़ाते हैं, बाण की चमक अंधकार में लंका की ओर जाती है"),
        DivinationCard(id: "rama_8", number: 8, suit: .dharma, deityID: .rama, nameEN: "Rama Rajya", nameZH: "理想王国", nameHI: "राम राज्य", meaningEN: "Ideal Kingdom", meaningZH: "圣治太平", meaningHI: "आदर्श राज्य", descEN: "The golden capital brings peace to all people, flowers rain from heaven and the land is endlessly fertile.", descZH: "金色国都万民安乐，天降花雨大地丰饶无尽", descHI: "स्वर्ण राजधानी में सभी लोग सुखी हैं, स्वर्ग से पुष्प वर्षा और धरती अनंत उर्वर"),

        DivinationCard(id: "rama_9", number: 9, suit: .karma, deityID: .rama, nameEN: "Vanvas", nameZH: "林中流放", nameHI: "वनवास", meaningEN: "Trial by Exile", meaningZH: "苦行试炼", meaningHI: "वनवास की परीक्षा", descEN: "Rama leads Sita and Lakshmana into the deep forest, clad in tree bark.", descZH: "罗摩携悉多与罗什曼踏入幽深密林身披树皮", descHI: "राम सीता और लक्ष्मण को गहन वन में ले जाते हैं, वल्कल वस्त्र पहने"),
        DivinationCard(id: "rama_10", number: 10, suit: .karma, deityID: .rama, nameEN: "Setu", nameZH: "跨海神桥", nameHI: "सेतु", meaningEN: "Bridge Built by Many", meaningZH: "众力成桥", meaningHI: "सबके प्रयास से सेतु", descEN: "The monkey army carries stones into the sea, boulders inscribed with holy names floating to form a great bridge to Lanka.", descZH: "猴军搬石投海巨石浮刻圣名长桥通向楞伽", descHI: "वानर सेना पत्थर समुद्र में डालती है, पवित्र नाम अंकित शिलाएं तैरकर लंका तक पुल बनाती हैं"),
        DivinationCard(id: "rama_11", number: 11, suit: .karma, deityID: .rama, nameEN: "Shabari Bhakti", nameZH: "夏芭丽果实", nameHI: "शबरी भक्ति", meaningEN: "Sincerity Rewarded", meaningZH: "诚心得报", meaningHI: "ईमानदारी का फल", descEN: "The forest elder woman offers pre-tasted berries to Rama, who accepts them with a smile.", descZH: "山林老妇以咬过的浆果敬奉罗摩神含笑纳受", descHI: "वन की बुजुर्ग महिला चखे हुए बेर राम को अर्पित करती है, राम मुस्कुराकर स्वीकार करते हैं"),
        DivinationCard(id: "rama_12", number: 12, suit: .karma, deityID: .rama, nameEN: "Ahalya Uddhar", nameZH: "解救阿诃利耶", nameHI: "अहल्या उद्धार", meaningEN: "Karma Dissolved", meaningZH: "因果化解", meaningHI: "कर्म का विलय", descEN: "Rama's toe touches the stone statue, the woman within regaining flesh and blood.", descZH: "罗摩足尖触碰石像石中女子重获血肉之身", descHI: "राम के पैर की अंगुली शिला स्पर्श करती है, पत्थर में स्त्री पुनः रक्त-मांस का शरीर पाती है"),
        DivinationCard(id: "rama_13", number: 13, suit: .karma, deityID: .rama, nameEN: "Jatayu Moksha", nameZH: "神鹰义殉", nameHI: "जटायु मोक्ष", meaningEN: "Sacrifice Bears Fruit", meaningZH: "舍身果报", meaningHI: "बलिदान का फल", descEN: "The great eagle falls broken-winged in a pool of blood, Rama cradles its body in final rites.", descZH: "巨鹰折翼倒于血泊罗摩抱其躯行最后之礼", descHI: "महान गरुड़ टूटे पंखों के साथ रक्त में गिरता है, राम उसके शरीर को अंतिम संस्कार के लिए गोद में लेते हैं"),
        DivinationCard(id: "rama_14", number: 14, suit: .karma, deityID: .rama, nameEN: "Sugriva Maitri", nameZH: "结盟须羯哩婆", nameHI: "सुग्रीव मैत्री", meaningEN: "Alliance of Mutual Aid", meaningZH: "互助之约", meaningHI: "पारस्परिक सहायता", descEN: "Rama and the monkey king circle the fire in oath, flames witnessing their bond of shared karma.", descZH: "罗摩与猴王绕火盟誓火焰见证因果相系之缘", descHI: "राम और वानर राज अग्नि की परिक्रमा कर शपथ लेते हैं, अग्नि उनके कर्म बंधन की साक्षी"),
        DivinationCard(id: "rama_15", number: 15, suit: .karma, deityID: .rama, nameEN: "Sita Haran", nameZH: "悉多遭劫", nameHI: "सीता हरण", meaningEN: "Evil Karma Invites Disaster", meaningZH: "恶业引祸", meaningHI: "बुरे कर्म विपत्ति लाते हैं", descEN: "The golden deer lures Sita beyond the boundary, the demon king's chariot snatches the queen into the sky.", descZH: "金鹿引悉多出界罗刹王驾车掠走王妃于空中", descHI: "स्वर्ण मृग सीता को सीमा से बाहर लुभाता है, राक्षस राज का रथ रानी को आकाश में छीन ले जाता है"),
        DivinationCard(id: "rama_16", number: 16, suit: .karma, deityID: .rama, nameEN: "Lanka Dahan", nameZH: "火烧楞伽", nameHI: "लंका दहन", meaningEN: "Karma Fire Spreads", meaningZH: "业火燎原", meaningHI: "कर्म अग्नि फैलती है", descEN: "Hanuman leaps across Lanka's rooftops with burning tail, the demon city engulfed in flames.", descZH: "哈努曼尾燃烈焰腾跃于楞伽城楼之上城池尽焚", descHI: "हनुमान जलती पूंछ से लंका की छतों पर कूदते हैं, राक्षस नगर अग्नि में समा जाता है"),

        DivinationCard(id: "rama_17", number: 17, suit: .kama, deityID: .rama, nameEN: "Sita Swayamvar", nameZH: "悉多择婿", nameHI: "सीता स्वयंवर", meaningEN: "Love's First Wish", meaningZH: "爱之初愿", meaningHI: "प्रेम की पहली इच्छा", descEN: "Sita holds a garland, her gaze passing over all the kings to the bow-wielding Rama.", descZH: "悉多手持花环目光越过众王望向举弓的罗摩", descHI: "सीता माला पकड़े हैं, उनकी दृष्टि सभी राजाओं को पार कर धनुष उठाने वाले राम पर जाती है"),
        DivinationCard(id: "rama_18", number: 18, suit: .kama, deityID: .rama, nameEN: "Hanuman Bhakti", nameZH: "哈努曼之忠", nameHI: "हनुमान भक्ति", meaningEN: "Supreme Devotion", meaningZH: "至诚归心", meaningHI: "परम भक्ति", descEN: "Hanuman tears open his chest, revealing the sacred image of Rama and Sita within his heart.", descZH: "哈努曼撕开胸膛心中显现罗摩与悉多的圣像", descHI: "हनुमान अपनी छाती फाड़ते हैं, हृदय में राम और सीता की पवित्र छवि प्रकट होती है"),
        DivinationCard(id: "rama_19", number: 19, suit: .kama, deityID: .rama, nameEN: "Sita Rama", nameZH: "悉多罗摩", nameHI: "सीता राम", meaningEN: "Sacred Love United", meaningZH: "圣爱合一", meaningHI: "पवित्र प्रेम एक", descEN: "Rama and Sita stand side by side, moonlight falling upon their clasped hands.", descZH: "罗摩与悉多并肩而立月光洒落于二人交握之手", descHI: "राम और सीता साथ-साथ खड़े हैं, चांदनी उनके जुड़े हाथों पर गिरती है"),
        DivinationCard(id: "rama_20", number: 20, suit: .kama, deityID: .rama, nameEN: "Bharata Viraha", nameZH: "婆罗多思念", nameHI: "भरत विरह", meaningEN: "Longing for Return", meaningZH: "望兄归来", meaningHI: "वापसी की तड़प", descEN: "Bharata places Rama's wooden sandals upon the throne, watching day and night for the path from the forest.", descZH: "婆罗多将罗摩木屐供于王座日夜守望林中归路", descHI: "भरत राम की खड़ाऊं सिंहासन पर रखते हैं, दिन-रात वन से आने वाले मार्ग की प्रतीक्षा करते हैं"),
        DivinationCard(id: "rama_21", number: 21, suit: .kama, deityID: .rama, nameEN: "Pushpaka Vimana", nameZH: "飞天神车", nameHI: "पुष्पक विमान", meaningEN: "Wishes Fulfilled Journey", meaningZH: "愿满归程", meaningHI: "इच्छापूर्ति की यात्रा", descEN: "The flower-adorned celestial chariot carries everyone over mountains and rivers, Sita leaning upon Rama.", descZH: "花饰天车载众人飞越山河悉多倚于罗摩身旁", descHI: "पुष्प सुशोभित दिव्य विमान सबको पर्वतों और नदियों के ऊपर ले जाता है, सीता राम पर टिकी हुई"),
        DivinationCard(id: "rama_22", number: 22, suit: .kama, deityID: .rama, nameEN: "Rama Nama", nameZH: "圣名持念", nameHI: "राम नाम", meaningEN: "Ceaseless Remembrance", meaningZH: "念念不离", meaningHI: "अविरत स्मरण", descEN: "Countless devotees chant Rama's name with joined palms, sound waves becoming golden rings of light.", descZH: "无数信众合掌低诵罗摩之名音波化为金色光圈", descHI: "अनगिनत भक्त हाथ जोड़कर राम नाम जपते हैं, ध्वनि तरंगें स्वर्ण प्रकाश वलय बनती हैं"),
        DivinationCard(id: "rama_23", number: 23, suit: .kama, deityID: .rama, nameEN: "Lakshmana Seva", nameZH: "罗什曼随侍", nameHI: "लक्ष्मण सेवा", meaningEN: "Brotherhood Devotion", meaningZH: "手足至情", meaningHI: "भ्रातृ भक्ति", descEN: "Lakshmana guards outside his brother's hut at night, bow in hand, gaze unwavering.", descZH: "罗什曼持弓夜守于兄嫂茅屋之外目光坚毅不移", descHI: "लक्ष्मण रात में भाई की कुटिया के बाहर पहरा देते हैं, धनुष हाथ में, दृष्टि अटल"),
        DivinationCard(id: "rama_24", number: 24, suit: .kama, deityID: .rama, nameEN: "Ayodhya Prabesh", nameZH: "归阿逾陀", nameHI: "अयोध्या प्रवेश", meaningEN: "All Wishes Granted", meaningZH: "众愿得偿", meaningHI: "सभी इच्छाएं पूर्ण", descEN: "Ten thousand oil lamps light the city gates, people lining the roads to welcome Rama's triumphant return.", descZH: "万盏油灯点亮城门民众夹道欢迎罗摩凯旋归国", descHI: "दस हजार दीप नगर द्वार को प्रकाशित करते हैं, लोग राम की विजयी वापसी का स्वागत करने सड़कों पर खड़े"),

        DivinationCard(id: "rama_25", number: 25, suit: .moksha, deityID: .rama, nameEN: "Agni Pariksha", nameZH: "烈火试炼", nameHI: "अग्नि परीक्षा", meaningEN: "Purification by Fire", meaningZH: "净火证真", meaningHI: "अग्नि से शुद्धि", descEN: "Sita stands within the blazing flames, the Fire God lifting her out unharmed.", descZH: "悉多端立于烈焰之中火神托举她完好无损而出", descHI: "सीता प्रज्वलित अग्नि में खड़ी हैं, अग्नि देव उन्हें अक्षत बाहर निकालते हैं"),
        DivinationCard(id: "rama_26", number: 26, suit: .moksha, deityID: .rama, nameEN: "Vishnu Avatar", nameZH: "毗湿奴化身", nameHI: "विष्णु अवतार", meaningEN: "Divine Nature Revealed", meaningZH: "神性显现", meaningHI: "दिव्य स्वरूप प्रकट", descEN: "Rama reveals his four-armed Vishnu form, holding conch, discus, lotus, and mace.", descZH: "罗摩现四臂毗湿奴法相持法螺金轮莲花神杵", descHI: "राम चतुर्भुज विष्णु रूप प्रकट करते हैं, शंख, चक्र, कमल और गदा धारण किए"),
        DivinationCard(id: "rama_27", number: 27, suit: .moksha, deityID: .rama, nameEN: "Saryu Prayan", nameZH: "入萨罗逾河", nameHI: "सरयू प्रयाण", meaningEN: "Returning to Source", meaningZH: "归返本源", meaningHI: "मूल में वापसी", descEN: "Rama steps into the golden river waters, radiance rising as his mortal body merges into infinite light.", descZH: "罗摩步入金色河水光芒升起肉身融入无尽之光", descHI: "राम स्वर्ण नदी जल में कदम रखते हैं, प्रकाश उठता है और नश्वर शरीर अनंत प्रकाश में विलीन होता है"),
        DivinationCard(id: "rama_28", number: 28, suit: .moksha, deityID: .rama, nameEN: "Rama Bana", nameZH: "罗摩神箭", nameHI: "राम बाण", meaningEN: "Piercing Ignorance", meaningZH: "断除无明", meaningHI: "अज्ञान का भेदन", descEN: "A golden arrow breaks through the void, piercing layers of darkness to reveal the bright emptiness beyond.", descZH: "一支金箭破空而出射穿层层黑暗露出光明虚空", descHI: "एक स्वर्ण बाण शून्य को भेदता है, अंधकार की परतें चीरकर उजले आकाश को प्रकट करता है"),
        DivinationCard(id: "rama_29", number: 29, suit: .moksha, deityID: .rama, nameEN: "Japa Mala", nameZH: "念珠持修", nameHI: "जप माला", meaningEN: "Steadying the Mind", meaningZH: "定心解缚", meaningHI: "मन को स्थिर करना", descEN: "A string of prayer beads floats above a lotus, each bead emitting a gentle glow.", descZH: "一串菩提念珠悬浮于莲花之上每颗珠子发出微光", descHI: "जप माला कमल के ऊपर तैरती है, हर मनका कोमल प्रकाश विकीर्ण करता है"),
        DivinationCard(id: "rama_30", number: 30, suit: .moksha, deityID: .rama, nameEN: "Tataka Vadha", nameZH: "降伏多吒迦", nameHI: "ताड़का वध", meaningEN: "Defeating Inner Demons", meaningZH: "破除魔障", meaningHI: "आंतरिक राक्षसों पर विजय", descEN: "Young Rama draws his bow against the roaring demoness, the forest returning to silence.", descZH: "少年罗摩张弓射向咆哮的女罗刹林中重归寂静", descHI: "किशोर राम गर्जना करती राक्षसी पर धनुष तानते हैं, वन पुनः शांत हो जाता है"),
        DivinationCard(id: "rama_31", number: 31, suit: .moksha, deityID: .rama, nameEN: "Guru Kripa", nameZH: "师恩加持", nameHI: "गुरु कृपा", meaningEN: "Teacher's Grace Awakens", meaningZH: "明师开悟", meaningHI: "गुरु कृपा से जागृति", descEN: "Sage Vishwamitra touches Rama's forehead, transmitting the sacred mantra.", descZH: "仙人毗湿瓦密多罗以手触罗摩之额传授神圣真言", descHI: "ऋषि विश्वामित्र राम के माथे को स्पर्श करते हैं, पवित्र मंत्र का संचार करते हैं"),
        DivinationCard(id: "rama_32", number: 32, suit: .moksha, deityID: .rama, nameEN: "Param Dham", nameZH: "至上归处", nameHI: "परम धाम", meaningEN: "Ultimate Liberation", meaningZH: "究竟解脱", meaningHI: "परम मुक्ति", descEN: "Within a golden wheel of light, Rama and Sita sit upon the lotus throne, all things returning to silent radiance.", descZH: "金色光轮中罗摩与悉多端坐莲台万物归于寂光", descHI: "स्वर्ण प्रकाश चक्र में राम और सीता कमल सिंहासन पर विराजमान, सभी वस्तुएं शांत दीप्ति में लौटती हैं"),
    ]
}
