import Foundation

extension DivinationCard {
    static let shivaCards: [DivinationCard] = [
        DivinationCard(id: "shiva_1", number: 1, suit: .dharma, deityID: .shiva, nameEN: "Trishula", nameZH: "三叉戟", nameHI: "त्रिशूल", meaningEN: "Three Paths of Dharma", meaningZH: "正法三道", meaningHI: "धर्म के तीन मार्ग", descEN: "The Trishula pierces through darkness, its three prongs guarding dharma, order, and truth.", descZH: "三叉戟刺破黑暗，三股锋刃守护法性、秩序与真理", descHI: "त्रिशूल अंधकार को भेदता है, इसके तीन शूल धर्म, व्यवस्था और सत्य की रक्षा करते हैं"),
        DivinationCard(id: "shiva_2", number: 2, suit: .dharma, deityID: .shiva, nameEN: "Nandi", nameZH: "南迪", nameHI: "नंदी", meaningEN: "Loyal to Righteousness", meaningZH: "忠诚正道", meaningHI: "धर्म के प्रति निष्ठा", descEN: "The sacred bull Nandi sits before the temple, his steadfast gaze eternally devoted to Shiva.", descZH: "神牛南迪端坐殿前，目光坚定地永恒守望湿婆", descHI: "पवित्र बैल नंदी मंदिर के सामने बैठा है, उसकी दृढ़ दृष्टि शिव की शाश्वत सेवा में"),
        DivinationCard(id: "shiva_3", number: 3, suit: .dharma, deityID: .shiva, nameEN: "Mount Kailash", nameZH: "冈仁波齐", nameHI: "कैलाश पर्वत", meaningEN: "Immovable Dharma Seat", meaningZH: "法座不动", meaningHI: "अचल धर्म आसन", descEN: "The silver snow-capped sacred mountain stands among the clouds, the ultimate abode where all dharma converges.", descZH: "银雪覆盖的神山矗立云端，万法归宗之圣所", descHI: "चांदी जैसी बर्फ से ढका पवित्र पर्वत बादलों में खड़ा है, जहां सभी धर्म एकत्र होते हैं"),
        DivinationCard(id: "shiva_4", number: 4, suit: .dharma, deityID: .shiva, nameEN: "Neelakantha", nameZH: "青颈大神", nameHI: "नीलकंठ", meaningEN: "Swallowing Poison to Protect", meaningZH: "吞毒护世", meaningHI: "विष पीकर रक्षा", descEN: "Shiva drinks the cosmic poison, his throat turning deep blue to protect all three worlds.", descZH: "湿婆仰饮毒海，喉咙化为深蓝以护三界苍生", descHI: "शिव विषैले समुद्र को पीते हैं, तीनों लोकों की रक्षा के लिए उनका कंठ गहरा नीला हो जाता है"),
        DivinationCard(id: "shiva_5", number: 5, suit: .dharma, deityID: .shiva, nameEN: "Tripurantaka", nameZH: "三城毁灭者", nameHI: "त्रिपुरांतक", meaningEN: "Destroying Evil, Upholding Right", meaningZH: "破邪立正", meaningHI: "बुराई का नाश, धर्म की स्थापना", descEN: "Shiva draws his bow and fires a flaming arrow, the three demon cities crumble in blazing fire.", descZH: "湿婆弯弓射出火箭，三座魔城于烈焰中崩灭", descHI: "शिव अपना धनुष खींचते हैं और अग्नि बाण छोड़ते हैं, तीनों असुर नगर भीषण अग्नि में ध्वस्त हो जाते हैं"),
        DivinationCard(id: "shiva_6", number: 6, suit: .dharma, deityID: .shiva, nameEN: "Dakshinamurti", nameZH: "南面尊师", nameHI: "दक्षिणामूर्ति", meaningEN: "Teaching Dharma in Silence", meaningZH: "默传正法", meaningHI: "मौन में धर्म शिक्षा", descEN: "Shiva sits facing south beneath the Bodhi tree, teaching the four sages through silence alone.", descZH: "湿婆南面而坐菩提树下，以静默为四圣贤说法", descHI: "शिव बोधि वृक्ष के नीचे दक्षिण की ओर मुख करके बैठे हैं, केवल मौन से चार ऋषियों को उपदेश देते हैं"),
        DivinationCard(id: "shiva_7", number: 7, suit: .dharma, deityID: .shiva, nameEN: "Pashupati", nameZH: "兽主", nameHI: "पशुपति", meaningEN: "Lord of All Beings", meaningZH: "众生怙主", meaningHI: "सभी प्राणियों के स्वामी", descEN: "Shiva sits cross-legged among all creatures, all beings finding refuge in the compassionate Lord.", descZH: "湿婆结跏趺坐于群兽之中，万物依止于慈悲法王", descHI: "शिव सभी प्राणियों के बीच पद्मासन में बैठे हैं, सभी जीव करुणामय स्वामी में शरण पाते हैं"),
        DivinationCard(id: "shiva_8", number: 8, suit: .dharma, deityID: .shiva, nameEN: "Vibhuti", nameZH: "圣灰", nameHI: "विभूति", meaningEN: "Pure Discipline", meaningZH: "戒行清净", meaningHI: "शुद्ध अनुशासन", descEN: "Three lines of ash painted across the forehead — after all attachments are burnt, only sacred vows remain.", descZH: "三道灰线横涂于额，焚尽执着后唯余神圣誓愿", descHI: "माथे पर तीन भस्म रेखाएं — सभी आसक्तियों के जलने के बाद केवल पवित्र संकल्प शेष रहते हैं"),

        DivinationCard(id: "shiva_9", number: 9, suit: .karma, deityID: .shiva, nameEN: "Nataraja", nameZH: "舞王", nameHI: "नटराज", meaningEN: "Dance of Karma", meaningZH: "业舞轮转", meaningHI: "कर्म का नृत्य", descEN: "Shiva dances within a ring of fire, one foot crushing the dwarf of ignorance.", descZH: "湿婆于火焰轮中起舞，一足踏碎无明之侏儒", descHI: "शिव अग्नि वलय में नृत्य करते हैं, एक पैर से अज्ञान के बौने को कुचलते हैं"),
        DivinationCard(id: "shiva_10", number: 10, suit: .karma, deityID: .shiva, nameEN: "Mahakala", nameZH: "大黑天", nameHI: "महाकाल", meaningEN: "Wheel of Time and Karma", meaningZH: "时轮业报", meaningHI: "समय और कर्म का चक्र", descEN: "The Lord of Time appears in wrathful form, driving the sun and moon and the karma of all things.", descZH: "时间之主现忿怒相，催动日月运转万物因果", descHI: "काल के स्वामी क्रोधी रूप में प्रकट होते हैं, सूर्य-चंद्र और सभी प्राणियों के कर्म को चलाते हैं"),
        DivinationCard(id: "shiva_11", number: 11, suit: .karma, deityID: .shiva, nameEN: "Damaru", nameZH: "达摩茹鼓", nameHI: "डमरू", meaningEN: "Resonance of Cause and Effect", meaningZH: "因果振响", meaningHI: "कारण और प्रभाव की गूंज", descEN: "The drum resonates through the void, each reverberation creating karmic force.", descZH: "拨浪鼓在虚空中震响，每一声回荡皆创生业力", descHI: "डमरू शून्य में गूंजता है, हर प्रतिध्वनि कर्म शक्ति उत्पन्न करती है"),
        DivinationCard(id: "shiva_12", number: 12, suit: .karma, deityID: .shiva, nameEN: "Agni Tandava", nameZH: "烈火之舞", nameHI: "अग्नि तांडव", meaningEN: "Burning Away Old Karma", meaningZH: "焚业化新", meaningHI: "पुराने कर्मों को जलाना", descEN: "Shiva sweeps through the old world with a dance of flames, new life sprouting from the ashes.", descZH: "湿婆以烈焰之舞席卷旧世，灰烬中萌发新生之芽", descHI: "शिव अग्नि नृत्य से पुरानी दुनिया को बहा ले जाते हैं, राख से नए जीवन के अंकुर फूटते हैं"),
        DivinationCard(id: "shiva_13", number: 13, suit: .karma, deityID: .shiva, nameEN: "Pinaka", nameZH: "天弓", nameHI: "पिनाक", meaningEN: "Power of Diligence", meaningZH: "精进之力", meaningHI: "परिश्रम की शक्ति", descEN: "Shiva draws the great bow full as the moon, the arrow aimed straight at sloth and delusion.", descZH: "湿婆挽开巨弓满弦如月，箭矢直指懈怠与迷障", descHI: "शिव विशाल धनुष को चंद्रमा की तरह खींचते हैं, बाण आलस्य और भ्रम की ओर लक्षित है"),
        DivinationCard(id: "shiva_14", number: 14, suit: .karma, deityID: .shiva, nameEN: "Ganas", nameZH: "群侍", nameHI: "गण", meaningEN: "Collective Effort", meaningZH: "众力成行", meaningHI: "सामूहिक प्रयास", descEN: "Countless attendants follow Shiva, working together to turn the wheel of the universe.", descZH: "无数侍从追随湿婆奔走，齐心协力推动宇宙之轮", descHI: "अनगिनत गण शिव का अनुसरण करते हैं, मिलकर ब्रह्मांड के चक्र को चलाते हैं"),
        DivinationCard(id: "shiva_15", number: 15, suit: .karma, deityID: .shiva, nameEN: "Sharabheshwara", nameZH: "人狮除暴", nameHI: "शरभेश्वर", meaningEN: "Karma Catches Up", meaningZH: "果报必至", meaningHI: "कर्मफल अवश्यम्भावी", descEN: "The eight-footed divine beast descends from heaven, subduing the rampaging lion with thunderous force.", descZH: "八足神兽自天而降，以雷霆之力制伏失控之狮", descHI: "आठ पैरों वाला दिव्य पशु स्वर्ग से उतरता है, वज्र शक्ति से उन्मत्त सिंह को वश में करता है"),
        DivinationCard(id: "shiva_16", number: 16, suit: .karma, deityID: .shiva, nameEN: "Vrishabha", nameZH: "公牛座骑", nameHI: "वृषभ", meaningEN: "Steady Right Action", meaningZH: "稳行正业", meaningHI: "स्थिर सत्कर्म", descEN: "Shiva rides the white bull across the earth, each step steady and unwavering.", descZH: "湿婆骑乘白牛踏过大地，每一步沉稳而坚定不移", descHI: "शिव सफेद बैल पर सवार होकर पृथ्वी पर चलते हैं, हर कदम स्थिर और अडिग"),

        DivinationCard(id: "shiva_17", number: 17, suit: .kama, deityID: .shiva, nameEN: "Ardhanarishvara", nameZH: "半女之主", nameHI: "अर्धनारीश्वर", meaningEN: "Union of Yin and Yang", meaningZH: "阴阳合愿", meaningHI: "यिन और यांग का मिलन", descEN: "Half-male, half-female united as one — left soft, right strong, merging into perfect love.", descZH: "半男半女之身合为一体，左柔右刚共融圆满之爱", descHI: "आधा पुरुष, आधी स्त्री एक में एकीकृत — बायां कोमल, दायां शक्तिशाली, पूर्ण प्रेम में विलीन"),
        DivinationCard(id: "shiva_18", number: 18, suit: .kama, deityID: .shiva, nameEN: "Ganga", nameZH: "恒河天降", nameHI: "गंगा", meaningEN: "Grace Flowing Like a River", meaningZH: "恩泽流愿", meaningHI: "नदी की तरह बहती कृपा", descEN: "The sacred river cascades from Shiva's hair, its sweet waters nourishing the thirsty heart.", descZH: "圣河自湿婆发髻倾泻而下，甘露之水润泽渴望之心", descHI: "पवित्र नदी शिव की जटाओं से बहती है, इसका मधुर जल प्यासे हृदय को तृप्त करता है"),
        DivinationCard(id: "shiva_19", number: 19, suit: .kama, deityID: .shiva, nameEN: "Uma-Maheshvara", nameZH: "大自在天眷", nameHI: "उमा-महेश्वर", meaningEN: "Sacred Partnership", meaningZH: "神圣伴侣", meaningHI: "पवित्र साझेदारी", descEN: "Shiva and Parvati sit side by side, their eyes meeting with infinite tenderness.", descZH: "湿婆与帕尔瓦蒂并肩而坐，四目相望含无尽深情", descHI: "शिव और पार्वती साथ-साथ बैठे हैं, उनकी दृष्टि में अनंत कोमलता"),
        DivinationCard(id: "shiva_20", number: 20, suit: .kama, deityID: .shiva, nameEN: "Kameshwara", nameZH: "爱欲之主", nameHI: "कामेश्वर", meaningEN: "Love Reborn Through Fire", meaningZH: "欲火重生", meaningHI: "अग्नि से पुनर्जन्मित प्रेम", descEN: "The god of love, burned by the Third Eye, is reborn — true love endures through the fire.", descZH: "爱神被第三眼焚毁后复活，真爱经烈火淬炼而永恒", descHI: "तीसरे नेत्र से भस्म कामदेव पुनर्जीवित होते हैं — सच्चा प्रेम अग्नि से गुजरकर शाश्वत बनता है"),
        DivinationCard(id: "shiva_21", number: 21, suit: .kama, deityID: .shiva, nameEN: "Somaskanda", nameZH: "圣家之主", nameHI: "सोमस्कंद", meaningEN: "Family Fulfillment", meaningZH: "家愿圆满", meaningHI: "पारिवारिक पूर्णता", descEN: "Between Shiva and Parvati sits their child Skanda, a picture of heavenly domestic bliss.", descZH: "湿婆与雪山女神之间端坐幼子室犍陀，天伦和乐", descHI: "शिव और पार्वती के बीच बालक स्कंद बैठे हैं, दिव्य पारिवारिक आनंद का चित्र"),
        DivinationCard(id: "shiva_22", number: 22, suit: .kama, deityID: .shiva, nameEN: "Rudraksha", nameZH: "金刚菩提", nameHI: "रुद्राक्ष", meaningEN: "Compassionate Tears Become Wishes", meaningZH: "悲泪化愿", meaningHI: "करुणा के आंसू इच्छा बनें", descEN: "Shiva's tears of compassion fall upon the earth, transforming into sacred Rudraksha seeds to protect all beings.", descZH: "湿婆慈悲之泪滴落大地，化为串串菩提籽护佑众生", descHI: "शिव के करुणा के आंसू पृथ्वी पर गिरते हैं, सभी प्राणियों की रक्षा के लिए पवित्र रुद्राक्ष बीज बन जाते हैं"),
        DivinationCard(id: "shiva_23", number: 23, suit: .kama, deityID: .shiva, nameEN: "Bhikshatana", nameZH: "托钵游行", nameHI: "भिक्षाटन", meaningEN: "Renunciation Reveals Love", meaningZH: "舍离得爱", meaningHI: "त्याग से प्रेम प्रकट", descEN: "Shiva wanders naked through the forest with his begging bowl, having renounced all, only pure longing remains.", descZH: "湿婆赤身持钵游于林间，万物皆舍唯余纯粹渴慕", descHI: "शिव अपने भिक्षा पात्र के साथ वन में विचरण करते हैं, सब कुछ त्यागकर केवल शुद्ध तड़प शेष"),
        DivinationCard(id: "shiva_24", number: 24, suit: .kama, deityID: .shiva, nameEN: "Chandrashekhara", nameZH: "月冠之主", nameHI: "चंद्रशेखर", meaningEN: "Gentle Light Soothes", meaningZH: "柔光抚慰", meaningHI: "कोमल प्रकाश शांत करता है", descEN: "The crescent moon rests upon Shiva's hair, its cool light washing over the dark night's heart.", descZH: "新月安卧于湿婆发髻之上，清辉如水照拂暗夜之心", descHI: "अर्धचंद्र शिव की जटाओं पर विराजमान है, इसकी शीतल चांदनी अंधेरी रात के हृदय को सहलाती है"),

        DivinationCard(id: "shiva_25", number: 25, suit: .moksha, deityID: .shiva, nameEN: "Third Eye", nameZH: "第三眼", nameHI: "तीसरा नेत्र", meaningEN: "Awakening Beyond Illusion", meaningZH: "破妄觉醒", meaningHI: "भ्रम से परे जागृति", descEN: "The celestial eye on the forehead suddenly opens — all illusions vanish in the fire of wisdom.", descZH: "额间天目倏然睁开，无明幻象在智慧烈焰中灰飞烟灭", descHI: "माथे पर दिव्य नेत्र अचानक खुलता है — सभी भ्रम ज्ञान की अग्नि में भस्म हो जाते हैं"),
        DivinationCard(id: "shiva_26", number: 26, suit: .moksha, deityID: .shiva, nameEN: "Mahayogi", nameZH: "大瑜伽士", nameHI: "महायोगी", meaningEN: "Liberation Through Meditation", meaningZH: "禅定解脱", meaningHI: "ध्यान से मुक्ति", descEN: "Shiva enters deep meditation atop the snow mountain, body covered in white ash, all thoughts stilled.", descZH: "湿婆于雪山之巅深入禅定，身覆白灰万念俱寂", descHI: "शिव हिमालय की चोटी पर गहन ध्यान में लीन हैं, शरीर पर सफेद भस्म, सभी विचार शांत"),
        DivinationCard(id: "shiva_27", number: 27, suit: .moksha, deityID: .shiva, nameEN: "Lingam", nameZH: "林伽", nameHI: "लिंगम", meaningEN: "Formless Absolute", meaningZH: "无相本体", meaningHI: "निराकार परम तत्व", descEN: "A pillar of light pierces heaven and earth, beginningless and endless — the ultimate reality beyond all form.", descZH: "光柱贯通天地无始无终，超越一切形相的究竟实在", descHI: "प्रकाश का स्तंभ स्वर्ग और पृथ्वी को भेदता है, अनादि और अनंत — सभी रूपों से परे परम सत्य"),
        DivinationCard(id: "shiva_28", number: 28, suit: .moksha, deityID: .shiva, nameEN: "Smashan", nameZH: "尸林修行", nameHI: "श्मशान", meaningEN: "Transcending Life and Death", meaningZH: "死生超越", meaningHI: "जीवन-मृत्यु से परे", descEN: "Shiva sits peacefully amid the ashes beside the cremation ground, realizing the imperishable in the place of death.", descZH: "湿婆安坐焚烧殿旁的灰烬中，于死亡之地证悟不灭", descHI: "शिव श्मशान के पास राख में शांति से बैठे हैं, मृत्यु के स्थान पर अविनाशी का साक्षात्कार करते हैं"),
        DivinationCard(id: "shiva_29", number: 29, suit: .moksha, deityID: .shiva, nameEN: "Nagendra", nameZH: "蛇王庄严", nameHI: "नागेंद्र", meaningEN: "Shedding Bonds for Freedom", meaningZH: "蜕缚解脱", meaningHI: "बंधनों से मुक्ति", descEN: "The cobra coils around Shiva's neck, shedding its old skin as the soul sheds its bonds.", descZH: "眼镜蛇盘绕湿婆颈项，蛇蜕旧皮如灵魂脱离束缚", descHI: "नाग शिव के गले में लिपटा है, जैसे आत्मा बंधनों को त्यागती है वैसे सांप पुरानी खाल छोड़ता है"),
        DivinationCard(id: "shiva_30", number: 30, suit: .moksha, deityID: .shiva, nameEN: "Digambara", nameZH: "虚空衣者", nameHI: "दिगंबर", meaningEN: "Naked Liberation", meaningZH: "赤裸解脱", meaningHI: "नग्न मुक्ति", descEN: "Shiva stands unclothed between heaven and earth — nothing can bind, nothing can attach.", descZH: "湿婆一丝不挂立于天地间，无物可缚无执可系", descHI: "शिव स्वर्ग और पृथ्वी के बीच निर्वस्त्र खड़े हैं — कुछ भी बांध नहीं सकता, कोई आसक्ति नहीं"),
        DivinationCard(id: "shiva_31", number: 31, suit: .moksha, deityID: .shiva, nameEN: "Omkara", nameZH: "唵声之源", nameHI: "ओंकार", meaningEN: "Primordial Sound Returns to Silence", meaningZH: "音振归寂", meaningHI: "आदि ध्वनि मौन में लौटती है", descEN: "The sacred syllable Om vibrates forth from the Damaru drum, all sounds returning to eternal silence.", descZH: "神圣音节唵从达摩茹鼓中振出，万籁归于永恒寂静", descHI: "पवित्र ॐ अक्षर डमरू से कंपित होता है, सभी ध्वनियां शाश्वत मौन में लौट जाती हैं"),
        DivinationCard(id: "shiva_32", number: 32, suit: .moksha, deityID: .shiva, nameEN: "Sadashiva", nameZH: "永恒吉祥", nameHI: "सदाशिव", meaningEN: "Ultimate Nirvana", meaningZH: "究竟涅槃", meaningHI: "परम निर्वाण", descEN: "Five-faced Shiva sits upon the lotus throne radiating great light, all cycles of existence come to perfect rest.", descZH: "五面湿婆端坐莲台放大光明，一切轮回于此圆满止息", descHI: "पंचमुखी शिव कमल सिंहासन पर विराजमान हैं महान प्रकाश विकीर्ण करते हुए, सभी संसार चक्र यहां पूर्ण विश्राम पाते हैं"),
    ]
}
