import Foundation

extension DivinationCard {
    static let vishnuCards: [DivinationCard] = [
        DivinationCard(id: "vishnu_1", number: 1, suit: .dharma, deityID: .vishnu, nameEN: "Narayana", nameZH: "那罗延", nameHI: "नारायण", meaningEN: "Supreme Cosmic Law", meaningZH: "至高法则", meaningHI: "सर्वोच्च ब्रह्मांडीय नियम", descEN: "Four-armed Vishnu sits upon the lotus throne, radiance illuminating all three worlds.", descZH: "四臂毗湿奴端坐莲台光芒遍照三界万物", descHI: "चतुर्भुज विष्णु कमल सिंहासन पर विराजमान हैं, दीप्ति तीनों लोकों को प्रकाशित करती है"),
        DivinationCard(id: "vishnu_2", number: 2, suit: .dharma, deityID: .vishnu, nameEN: "Sudarshana Chakra", nameZH: "善见神轮", nameHI: "सुदर्शन चक्र", meaningEN: "Cutting Through Unrighteousness", meaningZH: "斩断非法", meaningHI: "अधर्म का विनाश", descEN: "The flaming golden discus hovers at the tip of the divine finger, spinning with righteous fury.", descZH: "烈焰旋转的金色法轮悬于神之右指尖上", descHI: "ज्वलंत स्वर्ण चक्र दिव्य उंगली की नोक पर मंडराता है, धार्मिक क्रोध से घूमता है"),
        DivinationCard(id: "vishnu_3", number: 3, suit: .dharma, deityID: .vishnu, nameEN: "Matsya Avatar", nameZH: "摩蹉化身", nameHI: "मत्स्य अवतार", meaningEN: "Saving Dharma from Flood", meaningZH: "护法救世", meaningHI: "बाढ़ से धर्म की रक्षा", descEN: "A great golden fish holds the Vedic scriptures in its mouth amid the cosmic deluge.", descZH: "巨大金鱼衔住吠陀经典于滔天洪水之中", descHI: "विशाल स्वर्ण मछली ब्रह्मांडीय प्रलय के बीच वैदिक शास्त्रों को मुख में धारण करती है"),
        DivinationCard(id: "vishnu_4", number: 4, suit: .dharma, deityID: .vishnu, nameEN: "Kurma Avatar", nameZH: "俱利摩化身", nameHI: "कूर्म अवतार", meaningEN: "Supporting the Universe", meaningZH: "承载乾坤", meaningHI: "ब्रह्मांड का आधार", descEN: "The divine turtle sinks to the bottom of the milk ocean, supporting Mount Mandara upon its shell.", descZH: "神龟沉入乳海之底以龟背承托曼陀罗山", descHI: "दिव्य कछुआ क्षीर सागर की तलहटी में जाकर अपनी पीठ पर मंदराचल पर्वत को सहारा देता है"),
        DivinationCard(id: "vishnu_5", number: 5, suit: .dharma, deityID: .vishnu, nameEN: "Rama Avatar", nameZH: "罗摩化身", nameHI: "राम अवतार", meaningEN: "Dharma as King", meaningZH: "正法为王", meaningHI: "धर्म ही राजा", descEN: "Rama stands with the divine bow before the golden throne of Ayodhya.", descZH: "罗摩手执神弓端立于阿逾陀城金色王座前", descHI: "राम दिव्य धनुष लिए अयोध्या के स्वर्ण सिंहासन के सामने खड़े हैं"),
        DivinationCard(id: "vishnu_6", number: 6, suit: .dharma, deityID: .vishnu, nameEN: "Dharma Chakra", nameZH: "法之经纶", nameHI: "धर्म चक्र", meaningEN: "Cosmic Order Turns", meaningZH: "秩序运行", meaningHI: "ब्रह्मांडीय व्यवस्था चलती है", descEN: "The wheel of cosmic order turns eternally among the stars, never ceasing.", descZH: "宇宙秩序之轮于星辰间永恒转动不息", descHI: "ब्रह्मांडीय व्यवस्था का चक्र तारों के बीच शाश्वत रूप से घूमता है, कभी न रुकता"),
        DivinationCard(id: "vishnu_7", number: 7, suit: .dharma, deityID: .vishnu, nameEN: "Gada Mace", nameZH: "金刚宝杵", nameHI: "गदा", meaningEN: "Subduing Evil", meaningZH: "威伏邪恶", meaningHI: "बुराई का दमन", descEN: "The sacred mace blazes with magnificent flames, suppressing all forces of unrighteousness.", descZH: "神圣宝杵光焰万丈镇压一切不义之力", descHI: "पवित्र गदा भव्य ज्वालाओं से प्रज्वलित है, सभी अधार्मिक शक्तियों को दबाती है"),
        DivinationCard(id: "vishnu_8", number: 8, suit: .dharma, deityID: .vishnu, nameEN: "Varadaraja", nameZH: "赐恩之主", nameHI: "वरदराज", meaningEN: "Protecting All Beings", meaningZH: "庇护众生", meaningHI: "सभी प्राणियों की रक्षा", descEN: "Vishnu extends his lower right hand palm outward, granting the fearless protective blessing.", descZH: "毗湿奴伸出下右手掌心向外施无畏护法印", descHI: "विष्णु दाहिना हाथ हथेली बाहर की ओर बढ़ाते हैं, अभय रक्षा आशीर्वाद प्रदान करते हैं"),

        DivinationCard(id: "vishnu_9", number: 9, suit: .karma, deityID: .vishnu, nameEN: "Dashavatara", nameZH: "十大化身", nameHI: "दशावतार", meaningEN: "Manifesting as Needed", meaningZH: "应机示现", meaningHI: "आवश्यकतानुसार प्रकट", descEN: "Ten avatars arranged in sequence, from fish to Kalki, spanning all ages.", descZH: "十种化身依次排列从鱼至迦尔吉贯穿诸世", descHI: "दस अवतार क्रम में सजे हैं, मत्स्य से कल्कि तक, सभी युगों में व्याप्त"),
        DivinationCard(id: "vishnu_10", number: 10, suit: .karma, deityID: .vishnu, nameEN: "Kshira Sagara", nameZH: "乳海搅动", nameHI: "क्षीर सागर", meaningEN: "Karma Intertwined", meaningZH: "因果交织", meaningHI: "कर्म आपस में गुंथे", descEN: "Devas and Asuras churn the milk ocean together, various treasures emerging from the churning.", descZH: "天神与阿修罗合力搅动乳海翻涌出诸宝物", descHI: "देव और असुर मिलकर क्षीर सागर मंथन करते हैं, मंथन से विभिन्न रत्न निकलते हैं"),
        DivinationCard(id: "vishnu_11", number: 11, suit: .karma, deityID: .vishnu, nameEN: "Varaha Avatar", nameZH: "婆罗诃化身", nameHI: "वराह अवतार", meaningEN: "Mighty Rescue", meaningZH: "奋力拯救", meaningHI: "शक्तिशाली बचाव", descEN: "The great boar lifts the sunken earth from the abyss upon its tusks.", descZH: "巨大野猪从深渊中以獠牙托起沉没的大地", descHI: "विशाल वराह अपने दांतों पर रखकर डूबी हुई पृथ्वी को गहराई से उठाता है"),
        DivinationCard(id: "vishnu_12", number: 12, suit: .karma, deityID: .vishnu, nameEN: "Narasimha Avatar", nameZH: "人狮化身", nameHI: "नरसिंह अवतार", meaningEN: "Karma Manifests", meaningZH: "业报现前", meaningHI: "कर्मफल प्रकट", descEN: "The half-man, half-lion bursts from a stone pillar, subduing the demon king with divine fury.", descZH: "半人半狮从石柱中迸裂而出降伏魔王", descHI: "अर्ध-मानव, अर्ध-सिंह पत्थर के स्तंभ से प्रकट होते हैं, दिव्य क्रोध से राक्षस राज को पराजित करते हैं"),
        DivinationCard(id: "vishnu_13", number: 13, suit: .karma, deityID: .vishnu, nameEN: "Parashurama", nameZH: "持斧罗摩", nameHI: "परशुराम", meaningEN: "Decisive Action", meaningZH: "果断行动", meaningHI: "निर्णायक कर्म", descEN: "The axe-wielding warrior stands atop a mountain, sweeping away injustice with fearless force.", descZH: "持斧武士屹立山巅以无畏之力荡涤不公", descHI: "परशु धारी योद्धा पर्वत शिखर पर खड़े हैं, निडर शक्ति से अन्याय का सफाया करते हैं"),
        DivinationCard(id: "vishnu_14", number: 14, suit: .karma, deityID: .vishnu, nameEN: "Trivikrama", nameZH: "三步跨界", nameHI: "त्रिविक्रम", meaningEN: "Transcending Limits", meaningZH: "超越局限", meaningHI: "सीमाओं से परे", descEN: "The dwarf avatar instantly transforms into a giant, three steps spanning heaven, earth, and the netherworld.", descZH: "侏儒化身瞬间化为巨人三步丈量天地冥界", descHI: "वामन अवतार तत्काल विशालकाय रूप धारण करते हैं, तीन कदमों में स्वर्ग, पृथ्वी और पाताल को नापते हैं"),
        DivinationCard(id: "vishnu_15", number: 15, suit: .karma, deityID: .vishnu, nameEN: "Karma Phala", nameZH: "业之果实", nameHI: "कर्म फल", meaningEN: "Good and Evil Repaid", meaningZH: "善恶有报", meaningHI: "अच्छे-बुरे का फल", descEN: "Golden scales hang in the void, weighing the accumulated deeds of all beings across lifetimes.", descZH: "金色天秤悬于虚空称量众生累世之业行", descHI: "स्वर्ण तराजू शून्य में लटका है, सभी प्राणियों के जन्मों-जन्मों के कर्मों को तौलता है"),
        DivinationCard(id: "vishnu_16", number: 16, suit: .karma, deityID: .vishnu, nameEN: "Hayagriva", nameZH: "马头明王", nameHI: "हयग्रीव", meaningEN: "Wisdom Through Effort", meaningZH: "智慧精进", meaningHI: "प्रयास से ज्ञान", descEN: "The horse-headed deity chants the Vedas ceaselessly amid flames of wisdom.", descZH: "马首人身之神于光焰中诵持吠陀真知不辍", descHI: "अश्वमुखी देव ज्ञान की ज्वालाओं के बीच अविरत वेदों का पाठ करते हैं"),

        DivinationCard(id: "vishnu_17", number: 17, suit: .kama, deityID: .vishnu, nameEN: "Lakshmi Narayana", nameZH: "吉祥天眷", nameHI: "लक्ष्मी नारायण", meaningEN: "Sacred Love Wish", meaningZH: "神圣爱愿", meaningHI: "पवित्र प्रेम कामना", descEN: "Vishnu and Lakshmi sit together on a lotus, gazing at each other with deep divine affection.", descZH: "毗湿奴与吉祥天女并坐莲花彼此深情相望", descHI: "विष्णु और लक्ष्मी कमल पर साथ बैठे हैं, गहन दिव्य स्नेह से एक-दूसरे को निहारते हैं"),
        DivinationCard(id: "vishnu_18", number: 18, suit: .kama, deityID: .vishnu, nameEN: "Shankha", nameZH: "般遮阇那", nameHI: "शंख", meaningEN: "Awakening Heart's Desire", meaningZH: "唤醒心愿", meaningHI: "हृदय की इच्छा जागृत", descEN: "The sacred conch emits a deep, resonant sound that vibrates in the depths of the cosmos.", descZH: "神圣海螺发出悠远之音振荡于宇宙深处", descHI: "पवित्र शंख गहरी, गूंजती ध्वनि उत्पन्न करता है जो ब्रह्मांड की गहराइयों में कंपित होती है"),
        DivinationCard(id: "vishnu_19", number: 19, suit: .kama, deityID: .vishnu, nameEN: "Padmanabha", nameZH: "莲脐天尊", nameHI: "पद्मनाभ", meaningEN: "Creative Desire", meaningZH: "创造之愿", meaningHI: "सृजन की इच्छा", descEN: "Vishnu reclines on the serpent bed, a golden lotus blooming from his navel with Brahma seated upon it.", descZH: "毗湿奴卧于蛇床脐中金莲绽放梵天端坐其上", descHI: "विष्णु शेषनाग शय्या पर लेटे हैं, नाभि से स्वर्ण कमल खिलता है जिस पर ब्रह्मा विराजमान"),
        DivinationCard(id: "vishnu_20", number: 20, suit: .kama, deityID: .vishnu, nameEN: "Krishna Avatar", nameZH: "奎师那化身", nameHI: "कृष्ण अवतार", meaningEN: "Dance of Supreme Love", meaningZH: "至爱之舞", meaningHI: "परम प्रेम का नृत्य", descEN: "The dark-blue cowherd boy plays the sacred flute in a moonlit forest.", descZH: "深蓝牧童于满月夜的森林中奏响神圣笛音", descHI: "गहरे नीले गोपाल बालक चांदनी रात के वन में पवित्र बांसुरी बजाते हैं"),
        DivinationCard(id: "vishnu_21", number: 21, suit: .kama, deityID: .vishnu, nameEN: "Tulasi Mala", nameZH: "图拉西圣叶", nameHI: "तुलसी माला", meaningEN: "Devotional Offering", meaningZH: "虔诚奉献", meaningHI: "भक्तिपूर्ण अर्पण", descEN: "A garland of green sacred basil encircles the divine chest, exuding fragrance.", descZH: "翠绿圣罗勒花环环绕神之胸前散发芬芳", descHI: "हरी पवित्र तुलसी की माला दिव्य वक्ष को घेरती है, सुगंध बिखेरती है"),
        DivinationCard(id: "vishnu_22", number: 22, suit: .kama, deityID: .vishnu, nameEN: "Bhakti Yoga", nameZH: "奉爱瑜伽", nameHI: "भक्ति योग", meaningEN: "Surrendering Through Love", meaningZH: "以爱归依", meaningHI: "प्रेम से समर्पण", descEN: "A devotee with joined palms looks up at Vishnu, tears reflecting the divine image.", descZH: "虔信者双手合十仰望毗湿奴泪光中映出神容", descHI: "भक्त हाथ जोड़कर विष्णु की ओर देखता है, आंसुओं में दिव्य प्रतिबिंब झलकता है"),
        DivinationCard(id: "vishnu_23", number: 23, suit: .kama, deityID: .vishnu, nameEN: "Venugopala", nameZH: "牧牛笛音", nameHI: "वेणुगोपाल", meaningEN: "Longing of the Heart", meaningZH: "心之渴慕", meaningHI: "हृदय की तड़प", descEN: "At twilight by the river, the flute sings its long melody, cows resting, gopis listening with rapt hearts.", descZH: "黄昏河畔笛声悠扬牛群安卧牧女倾心而听", descHI: "सांझ के नदी किनारे बांसुरी की लंबी धुन गूंजती है, गायें विश्राम करती हैं, गोपियां मंत्रमुग्ध सुनती हैं"),
        DivinationCard(id: "vishnu_24", number: 24, suit: .kama, deityID: .vishnu, nameEN: "Srinivasa", nameZH: "圣吉祥主", nameHI: "श्रीनिवास", meaningEN: "Wish Power Fulfilled", meaningZH: "愿力成就", meaningHI: "कामना शक्ति पूर्ण", descEN: "Vishnu smiles serenely atop the seven hills, answering the prayers of all beings.", descZH: "七丘之巅的毗湿奴庄严微笑回应众生祈愿", descHI: "विष्णु सात पहाड़ियों पर शांत मुस्कान से सभी प्राणियों की प्रार्थनाओं का उत्तर देते हैं"),

        DivinationCard(id: "vishnu_25", number: 25, suit: .moksha, deityID: .vishnu, nameEN: "Ananta Shesha", nameZH: "阿难陀龙蛇", nameHI: "अनंत शेष", meaningEN: "Endless Transcendence", meaningZH: "无尽超越", meaningHI: "अनंत उत्कर्ष", descEN: "The thousand-headed serpent coils upon eternal waters, sheltering the sleeping deity with an infinite canopy.", descZH: "千首巨蛇盘踞于永恒之水上为沉睡之神张伞", descHI: "सहस्र मस्तक वाला नाग शाश्वत जल पर कुंडली मारे है, सोते देव के ऊपर अनंत छत्र धारण किए"),
        DivinationCard(id: "vishnu_26", number: 26, suit: .moksha, deityID: .vishnu, nameEN: "Garuda", nameZH: "迦楼罗神鹰", nameHI: "गरुड़", meaningEN: "Soaring Free", meaningZH: "自在飞升", meaningHI: "स्वतंत्र उड़ान", descEN: "The golden eagle spreads its wings soaring above the sea of clouds, transcending all bonds.", descZH: "金翅大鹏展翼翱翔于云海之上超越一切束缚", descHI: "स्वर्ण गरुड़ पंख फैलाकर बादलों के सागर के ऊपर उड़ता है, सभी बंधनों से परे"),
        DivinationCard(id: "vishnu_27", number: 27, suit: .moksha, deityID: .vishnu, nameEN: "Vaikuntha", nameZH: "毗恭达天国", nameHI: "वैकुंठ", meaningEN: "Ultimate Liberation", meaningZH: "究竟解脱", meaningHI: "परम मुक्ति", descEN: "A golden celestial palace stands in infinite light, countless liberated souls dwelling in peace.", descZH: "黄金天宫矗立于无尽光明中万千解脱者安住", descHI: "स्वर्ण दिव्य महल अनंत प्रकाश में खड़ा है, अनगिनत मुक्त आत्माएं शांति में निवास करती हैं"),
        DivinationCard(id: "vishnu_28", number: 28, suit: .moksha, deityID: .vishnu, nameEN: "Yoga Nidra", nameZH: "瑜伽睡眠", nameHI: "योग निद्रा", meaningEN: "Dissolving into Truth", meaningZH: "寂灭归真", meaningHI: "सत्य में विलय", descEN: "Vishnu closes his eyes and reclines upon the boundless waters as the universe dissolves.", descZH: "毗湿奴于宇宙消融之际闭目安卧于无边之水", descHI: "विष्णु ब्रह्मांड के विलय के समय आंखें बंद कर असीम जल पर लेटे हैं"),
        DivinationCard(id: "vishnu_29", number: 29, suit: .moksha, deityID: .vishnu, nameEN: "Vishvarupa", nameZH: "宇宙神相", nameHI: "विश्वरूप", meaningEN: "All Forms Return to One", meaningZH: "万相归一", meaningHI: "सभी रूप एक में लौटते हैं", descEN: "All cosmic phenomena manifest within Vishnu's vast body — infinite universes contained in one form.", descZH: "无限宇宙万象皆显现于毗湿奴巨大的身躯之中", descHI: "सभी ब्रह्मांडीय घटनाएं विष्णु के विशाल शरीर में प्रकट होती हैं — एक रूप में अनंत ब्रह्मांड समाहित"),
        DivinationCard(id: "vishnu_30", number: 30, suit: .moksha, deityID: .vishnu, nameEN: "Buddha Avatar", nameZH: "佛陀化身", nameHI: "बुद्ध अवतार", meaningEN: "Enlightened Liberation", meaningZH: "觉悟解脱", meaningHI: "प्रबुद्ध मुक्ति", descEN: "The enlightened one enters deep meditation beneath the Bodhi tree, radiating compassion and wisdom.", descZH: "觉者于菩提树下入深定放射慈悲智慧之光", descHI: "प्रबुद्ध बोधि वृक्ष के नीचे गहन ध्यान में प्रवेश करते हैं, करुणा और ज्ञान का प्रकाश विकीर्ण करते हैं"),
        DivinationCard(id: "vishnu_31", number: 31, suit: .moksha, deityID: .vishnu, nameEN: "Kalki Avatar", nameZH: "迦尔吉化身", nameHI: "कल्कि अवतार", meaningEN: "Ultimate Renewal", meaningZH: "终极更新", meaningHI: "परम नवीनीकरण", descEN: "The white horse rider descends with sword into the darkness of the end times, ushering in a new era.", descZH: "白马骑士持剑降临于末世黑暗开启全新纪元", descHI: "श्वेत अश्व सवार तलवार लेकर अंतिम युग के अंधकार में अवतरित होते हैं, नए युग का आरंभ करते हैं"),
        DivinationCard(id: "vishnu_32", number: 32, suit: .moksha, deityID: .vishnu, nameEN: "Paramapada", nameZH: "至上归处", nameHI: "परमपद", meaningEN: "Perfect Nirvana", meaningZH: "圆满涅槃", meaningHI: "पूर्ण निर्वाण", descEN: "The soul transforms into a point of light, merging into Vishnu's boundless golden ocean of radiance.", descZH: "灵魂化为光点融入毗湿奴无边金色光海之中", descHI: "आत्मा प्रकाश बिंदु में रूपांतरित होकर विष्णु के असीम स्वर्ण प्रकाश सागर में विलीन होती है"),
    ]

    static func allCards(for deityID: DeityID) -> [DivinationCard] {
        switch deityID {
        case .shiva: return shivaCards
        case .hanuman: return hanumanCards
        case .ganesha: return ganeshaCards
        case .lakshmi: return lakshmiCards
        case .rama: return ramaCards
        case .krishna: return krishnaCards
        case .vishnu: return vishnuCards
        }
    }
}
